# Generated by Django 6.0.7 on 2026-07-29 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0003_documentoliberacion'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liberacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('liberado', 'Liberado'), ('liberado_concesion', 'Liberado bajo concesión'), ('rechazado', 'Rechazado')], default='pendiente', max_length=25, verbose_name='Estado')),
                ('autorizada_en', models.DateTimeField(blank=True, null=True, verbose_name='Autorizada en')),
                ('concesion', models.BooleanField(default=False, help_text='Marca permanente: el producto salió sin ser conforme', verbose_name='Bajo concesión')),
                ('motivo_concesion', models.TextField(blank=True, help_text='Obligatorio si es una concesión', verbose_name='Motivo de la concesión')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('autorizada_por', models.ForeignKey(blank=True, help_text='Rol calidad o admin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to=settings.AUTH_USER_MODEL, verbose_name='Autorizada por')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liberacion', to='produccion.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Liberación de producto',
                'verbose_name_plural': 'Liberaciones de producto',
                'ordering': ['-autorizada_en', 'lote'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completado', 'Completado'), ('observado', 'Observado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('valores', models.JSONField(blank=True, default=dict, help_text='{clave del campo de la plantilla: valor}', verbose_name='Valores del formulario')),
                ('referencia', models.CharField(blank=True, help_text='N.º del documento físico o externo, si lo hay', max_length=120, verbose_name='Referencia')),
                ('completado_en', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_calidad', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='maestros.documentoliberacion', verbose_name='Documento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_calidad', to='produccion.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Registro de calidad',
                'verbose_name_plural': 'Registros de calidad',
                'ordering': ['lote', 'documento__orden'],
                'constraints': [models.UniqueConstraint(fields=('lote', 'documento'), name='registro_calidad_unico_por_lote_y_documento')],
            },
        ),
    ]
