# Generated by Django 6.0.7 on 2026-07-31 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
        ('maestros', '0015_documentoliberacion_frecuencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del registro')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Solo para los registros «según programa»: hasta cuándo cubre', null=True, verbose_name='Vigente hasta')),
                ('turno', models.CharField(blank=True, max_length=5, verbose_name='Turno')),
                ('valores', models.JSONField(blank=True, default=dict, verbose_name='Valores del formulario')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completado', 'Completado'), ('observado', 'Observado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('completado_en', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_equipo', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_equipo', to='maestros.documentoliberacion', verbose_name='Documento')),
                ('equipo', models.ForeignKey(blank=True, help_text='Vacío cuando el registro no es de una máquina concreta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='maestros.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Registro de equipo',
                'verbose_name_plural': 'Registros de equipo',
                'ordering': ['-fecha', 'documento__orden'],
                'constraints': [models.UniqueConstraint(fields=('documento', 'equipo', 'fecha', 'turno'), name='registro_equipo_unico_por_periodo')],
            },
        ),
    ]
