# Generated by Django 6.0.7 on 2026-09-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0005_liberacionproceso_por_salida'),
        ('produccion', '0014_pallet_kg_maximo_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacionproceso',
            name='analisis_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones_proceso', to='produccion.analisis'),
        ),
    ]
