"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

from .seguridad import (
    exigir_postgresql,
    normalizar_entorno,
    validar_entorno_endurecido,
)


def env_bool(nombre, predeterminado=False):
    """Lee una variable booleana con valores habituales de despliegue."""
    valor = os.environ.get(nombre)
    if valor is None:
        return predeterminado
    return valor.lower() in ("1", "true", "yes", "on")


def env_lista(nombre, predeterminado=""):
    """Convierte una lista separada por comas y elimina entradas vacías."""
    return [
        elemento.strip()
        for elemento in os.environ.get(nombre, predeterminado).split(",")
        if elemento.strip()
    ]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# La configuracion que cambia entre equipos vive en backend/.env, que no se
# versiona. backend/.env.example lista las variables con valores de ejemplo.
load_dotenv(BASE_DIR / ".env")

DJANGO_ENV = normalizar_entorno(os.environ.get("DJANGO_ENV"))

# La suite histórica crea tokens de DRF directamente en varios fixtures. La
# aplicación real ya no los emite ni los acepta: usa ``SesionUsuario`` y guarda
# solo el hash de la credencial. Mantener este adaptador exclusivamente durante
# ``manage.py test`` permite migrar los fixtures sin abrir una segunda vía de
# autenticación en desarrollo o producción. Las pruebas dedicadas de sesiones
# siguen recorriendo el mecanismo real.
PERMITIR_TOKEN_DRF_LEGACY_EN_PRUEBAS = "test" in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-w^a-=_$-k*9_x6j8+t+8x40i9ua$h1@knw#2sr#&%u5k-w=z3#",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_lista("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'maestros',
    'produccion',
    'recepcion',
    'recoleccion',
    'estandarizacion',
    'calidad',
    'inocuidad',
    'inventario',
    'planificacion',
    'auditoria',
    'observabilidad',
    'procesos',
    'mantenimiento',
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Va al final: necesita el usuario ya resuelto por
    # AuthenticationMiddleware, y envuelve a la vista para soltar el
    # actor pase lo que pase.
    'auditoria.middleware.AuditoriaMiddleware',
]

# --------------------------------------------------------------- medición
#
# Apagada por omisión: se enciende para medir y se apaga después. Con
# `METRICAS_ACTIVAS` en falso el middleware ni siquiera entra en la cadena
# —lanza `MiddlewareNotUsed`—, así que apagado no cuesta una llamada por
# request: cuesta cero.
#
# Va **después** de AuditoriaMiddleware para medir el request completo,
# incluido lo que la auditoría escribe. Medir por dentro daría un número más
# bonito y menos cierto.
METRICAS_ACTIVAS = os.getenv("METRICAS_ACTIVAS", "").strip().lower() in {"1", "true"}
METRICAS_ARCHIVO = os.getenv("METRICAS_ARCHIVO", "metricas.jsonl")

if METRICAS_ACTIVAS:
    MIDDLEWARE = MIDDLEWARE + ["observabilidad.middleware.MetricasMiddleware"]

    # `disable_existing_loggers` en falso: apagar los demás loggers por
    # encender la medición dejaría al servidor mudo justo mientras se mide.
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {"crudo": {"format": "%(message)s"}},
        "handlers": {
            "metricas": {
                "class": "logging.FileHandler",
                "filename": METRICAS_ARCHIVO,
                "encoding": "utf-8",
                "formatter": "crudo",
            }
        },
        "loggers": {
            "metricas": {
                "handlers": ["metricas"],
                "level": "INFO",
                # Sin propagar: si no, cada medición sale también por la
                # consola y el registro del servidor se vuelve ilegible.
                "propagate": False,
            }
        },
    }

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL no es una preferencia de despliegue: sus bloqueos de fila y
# restricciones forman parte de las reglas de negocio. No existe fallback.
DB_ENGINE = os.getenv("DB_ENGINE", "postgresql")
# Se acepta una URL de conexión para proveedores PostgreSQL administrados.
# DATABASE_URL conserva prioridad; la URL sin pool es una última alternativa.
DATABASE_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_URL")
    or os.getenv("DATABASE_URL_UNPOOLED")
)

DATABASE_VARIABLES = ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT")
DATABASE_CONFIGURED = bool(DATABASE_URL) or all(
    os.getenv(nombre) for nombre in DATABASE_VARIABLES
)
DB_CONN_MAX_AGE = int(os.getenv("DB_CONN_MAX_AGE", "60"))

if DATABASE_URL:
    # Algunos proveedores entregan la conexion completa en DATABASE_URL.
    # Tiene prioridad sobre las variables DB_* individuales.
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "ccaa"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "CONN_MAX_AGE": DB_CONN_MAX_AGE,
            "CONN_HEALTH_CHECKS": True,
        }
    }

    # En un servidor remoto la conexion va cifrada. Solo se declara si viene
    # en el entorno: en local, exigir SSL impediria conectarse.
    if os.getenv("DB_SSLMODE"):
        DATABASES["default"]["OPTIONS"] = {"sslmode": os.getenv("DB_SSLMODE")}

exigir_postgresql(DB_ENGINE, DATABASES["default"]["ENGINE"])


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MAX_UPLOAD_SIZE = int(os.environ.get("DJANGO_MAX_UPLOAD_MB", "15")) * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = min(MAX_UPLOAD_SIZE, 5 * 1024 * 1024)


# Recuperación de contraseña
#
# El backend genera y valida el token; el frontend solo presenta el formulario
# al que apunta este enlace. En producción estas opciones se configuran desde
# variables de entorno.
PASSWORD_RESET_FRONTEND_URL = os.environ.get(
    "PASSWORD_RESET_FRONTEND_URL",
    "http://localhost:5173/#/restablecer-contrasena",
)
PASSWORD_RESET_TIMEOUT = int(os.environ.get("PASSWORD_RESET_TIMEOUT", "3600"))

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "no-responder@camposaustrales.cl",
)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "usuarios.email_backends.MicrosoftGraphEmailBackend",
)
MICROSOFT_GRAPH_TENANT_ID = os.environ.get("MICROSOFT_GRAPH_TENANT_ID", "")
MICROSOFT_GRAPH_CLIENT_ID = os.environ.get("MICROSOFT_GRAPH_CLIENT_ID", "")
MICROSOFT_GRAPH_CLIENT_SECRET = os.environ.get(
    "MICROSOFT_GRAPH_CLIENT_SECRET",
    "",
)
MICROSOFT_GRAPH_SENDER = os.environ.get("MICROSOFT_GRAPH_SENDER", "")
MICROSOFT_GRAPH_TIMEOUT = int(os.environ.get("MICROSOFT_GRAPH_TIMEOUT", "15"))
MICROSOFT_GRAPH_SAVE_TO_SENT_ITEMS = (
    os.environ.get("MICROSOFT_GRAPH_SAVE_TO_SENT_ITEMS", "false").lower()
    in ("1", "true", "yes")
)

CORS_ALLOWED_ORIGINS = env_lista(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173",
)
CSRF_TRUSTED_ORIGINS = env_lista("CSRF_TRUSTED_ORIGINS")

# Endurecimiento activado automáticamente al usar DJANGO_DEBUG=false.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# Cuantos proxies de confianza hay delante de la aplicacion.
#
# **De esto depende que el limite por IP no sea esquivable.** Sin declararlo,
# DRF usa la cabecera `X-Forwarded-For` **entera** como identidad; detras de
# Nginx, quien ataca manda una cabecera distinta en cada peticion, Nginx le
# anade la suya, la cadena cambia siempre y cada intento estrena cubo: el
# limite existe y no frena nada.
#
# Con el numero declarado se toma la entrada que anadio **nuestro** proxy --la
# ultima--, la unica que el cliente no puede escribir.
#
# Cero por defecto: sin proxy manda `REMOTE_ADDR` y no se cree ninguna
# cabecera. Es el fallo seguro. El despliegue con Nginx tiene que poner 1, y si
# se olvida el sintoma es un limite demasiado estricto --toda la planta
# comparte cubo-- que se nota, en vez de uno inexistente que no se nota.
PROXIES_DE_CONFIANZA = int(os.environ.get("PROXIES_DE_CONFIANZA", "0"))

REST_FRAMEWORK = {
    # Los listados van paginados: el historico de produccion son ~954 lotes y
    # va a seguir creciendo. Sin esto, /lotes/ devolveria la tabla entera.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,

    # Sin esto DRF usa la cabecera `X-Forwarded-For` entera como identidad y el
    # limite por IP se esquiva mandando una distinta cada vez.
    "NUM_PROXIES": PROXIES_DE_CONFIANZA,

    # Toda la API exige identificarse. Las excepciones se declaran una por una
    # en su vista (login y recuperación de contraseña), nunca al revés: si un
    # endpoint nuevo olvida declarar permisos, queda cerrado en vez de abierto.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "usuarios.authentication.TokenAuthenticationConScope",
        # Sesion tambien, para poder navegar la API desde el navegador
        # estando logueado en /admin/.
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "password_reset_request": "5/hour",
        "password_reset_confirm": "10/hour",

        # Login. Dos limites porque protegen de cosas distintas:
        #
        # - Por direccion, holgado: la planta sale a internet por una sola IP,
        #   asi que treinta personas comparten cuota. Apretarlo aqui deja al
        #   turno entero fuera por culpa de un atacante, que es una denegacion
        #   de servicio servida en bandeja.
        # - Por nombre de usuario, estricto: una persona no falla quince veces
        #   en una hora contra su propia cuenta. Es el que sobrevive a un
        #   atacante que rota direcciones, que es lo habitual.
        "login_ip": os.environ.get("THROTTLE_LOGIN_IP", "60/hour"),
        "login_usuario": os.environ.get("THROTTLE_LOGIN_USUARIO", "15/hour"),
    },
}


# La actividad se persiste por intervalos, no en cada request, para evitar
# escrituras innecesarias en PostgreSQL.
SESSION_IDLE_TIMEOUT_MINUTES = int(os.environ.get("SESSION_IDLE_TIMEOUT_MINUTES", "60"))
SESSION_ABSOLUTE_TIMEOUT_HOURS = int(os.environ.get("SESSION_ABSOLUTE_TIMEOUT_HOURS", "12"))
SESSION_ACTIVITY_UPDATE_SECONDS = int(os.environ.get("SESSION_ACTIVITY_UPDATE_SECONDS", "120"))


# Celery
#
# Existe para sacar el MRP semanal de la peticion HTTP: la explosion multinivel
# de una semana ocupaba un worker de Gunicorn de principio a fin, y con dos
# workers eso deja al resto de la planta esperando.
#
# **Sin `CELERY_BROKER_URL` corre en modo `eager`**: la tarea se ejecuta en el
# momento, dentro de la peticion, igual que antes. Es lo que permite desplegar
# este codigo antes de que llegue la fase de Redis, y que las pruebas y el
# entorno local no necesiten infraestructura.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "")
CELERY_TASK_ALWAYS_EAGER = not CELERY_BROKER_URL

# En modo `eager` una excepcion de la tarea se propaga a quien la llamo. Se
# apaga: la tarea ya guarda su propio fallo en la ejecucion, y dejarla propagar
# haria que el mismo error se comportara distinto con worker y sin el.
CELERY_TASK_EAGER_PROPAGATES = False

# El resultado no se guarda en Celery: el estado y los datos del MRP viven en
# `EjecucionMRP`, que es donde la pantalla los consulta. Un segundo lugar donde
# mirar el mismo hecho es un sitio donde discrepar.
CELERY_RESULT_BACKEND = None
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE

# Una tarea que no termina en veinte minutos es una tarea rota. Sin techo, un
# calculo colgado retiene un worker para siempre.
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", "1200"))
CELERY_BEAT_SCHEDULE = {
    "alertas-operacionales-cada-hora": {
        "task": "inventario.tareas.refrescar_alertas_operacionales",
        "schedule": 3600.0,
    },
}


# Caché
#
# **De esto depende que los limites de arriba existan.** `SimpleRateThrottle`
# cuenta en la cache; sin declarar ninguna, Django usa `LocMemCache`, que vive
# en la memoria de un proceso. Con varios workers de Gunicorn --y mas aun con
# varias replicas-- un limite de «15 por hora» se convierte en «15 por hora y
# por worker»: existe en el codigo y no en la practica.
#
# Se usa PostgreSQL y no Redis porque ya esta ahi: es compartida, que es la
# propiedad que hace falta, y no agrega infraestructura que mantener hoy.
# `CACHE_URL` deja pasar a Redis sin tocar codigo cuando llegue su fase.
CACHE_URL = os.environ.get("CACHE_URL", "")

if CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": CACHE_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "cache_ccaa",
            # Las entradas de throttle son pequenas y caducan solas. El techo
            # evita que la tabla crezca sin limite si se cachea algo mas.
            "OPTIONS": {"MAX_ENTRIES": 10000},
        }
    }

validar_entorno_endurecido(
    DJANGO_ENV,
    {
        "DEBUG": DEBUG,
        "SECRET_KEY": SECRET_KEY,
        "ALLOWED_HOSTS": ALLOWED_HOSTS,
        "SECURE_SSL_REDIRECT": SECURE_SSL_REDIRECT,
        "SESSION_COOKIE_SECURE": SESSION_COOKIE_SECURE,
        "CSRF_COOKIE_SECURE": CSRF_COOKIE_SECURE,
        "SECURE_HSTS_SECONDS": SECURE_HSTS_SECONDS,
        "CSRF_TRUSTED_ORIGINS": CSRF_TRUSTED_ORIGINS,
        "DATABASE_CONFIGURED": DATABASE_CONFIGURED,
    },
)
