"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

from .seguridad import (
    exigir_postgresql,
    normalizar_entorno,
    validar_entorno_endurecido,
)


def env_bool(nombre, predeterminado=False):
    """Lee una variable booleana con valores habituales de despliegue."""
    valor = os.environ.get(nombre)
    if valor is None:
        return predeterminado
    return valor.lower() in ("1", "true", "yes", "on")


def env_lista(nombre, predeterminado=""):
    """Convierte una lista separada por comas y elimina entradas vacías."""
    return [
        elemento.strip()
        for elemento in os.environ.get(nombre, predeterminado).split(",")
        if elemento.strip()
    ]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# La configuracion que cambia entre equipos vive en backend/.env, que no se
# versiona. backend/.env.example lista las variables con valores de ejemplo.
load_dotenv(BASE_DIR / ".env")

DJANGO_ENV = normalizar_entorno(os.environ.get("DJANGO_ENV"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-w^a-=_$-k*9_x6j8+t+8x40i9ua$h1@knw#2sr#&%u5k-w=z3#",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_lista("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'maestros',
    'produccion',
    'recepcion',
    'recoleccion',
    'estandarizacion',
    'calidad',
    'inocuidad',
    'inventario',
    'planificacion',
    'auditoria',
    'procesos',
    'mantenimiento',
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Va al final: necesita el usuario ya resuelto por
    # AuthenticationMiddleware, y envuelve a la vista para soltar el
    # actor pase lo que pase.
    'auditoria.middleware.AuditoriaMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL no es una preferencia de despliegue: sus bloqueos de fila y
# restricciones forman parte de las reglas de negocio. No existe fallback.
DB_ENGINE = os.getenv("DB_ENGINE", "postgresql")
# Neon/Vercel puede publicar la conexión con cualquiera de estos nombres.
# DATABASE_URL conserva prioridad; la URL sin pool es una última alternativa.
DATABASE_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_URL")
    or os.getenv("DATABASE_URL_UNPOOLED")
)

DATABASE_VARIABLES = ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT")
DATABASE_CONFIGURED = bool(DATABASE_URL) or all(
    os.getenv(nombre) for nombre in DATABASE_VARIABLES
)

if DATABASE_URL:
    # Vercel Marketplace (por ejemplo Neon) entrega la conexion completa en
    # DATABASE_URL. Tiene prioridad sobre las variables DB_* individuales.
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "0")),
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "ccaa"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }

    # En un servidor remoto la conexion va cifrada. Solo se declara si viene
    # en el entorno: en local, exigir SSL impediria conectarse.
    if os.getenv("DB_SSLMODE"):
        DATABASES["default"]["OPTIONS"] = {"sslmode": os.getenv("DB_SSLMODE")}

exigir_postgresql(DB_ENGINE, DATABASES["default"]["ENGINE"])


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MAX_UPLOAD_SIZE = int(os.environ.get("DJANGO_MAX_UPLOAD_MB", "15")) * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = min(MAX_UPLOAD_SIZE, 5 * 1024 * 1024)


# Recuperación de contraseña
#
# El backend genera y valida el token; el frontend solo presenta el formulario
# al que apunta este enlace. En producción estas opciones se configuran desde
# variables de entorno.
PASSWORD_RESET_FRONTEND_URL = os.environ.get(
    "PASSWORD_RESET_FRONTEND_URL",
    "http://localhost:5173/#/restablecer-contrasena",
)
PASSWORD_RESET_TIMEOUT = int(os.environ.get("PASSWORD_RESET_TIMEOUT", "3600"))

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "no-responder@camposaustrales.cl",
)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "usuarios.email_backends.MicrosoftGraphEmailBackend",
)
MICROSOFT_GRAPH_TENANT_ID = os.environ.get("MICROSOFT_GRAPH_TENANT_ID", "")
MICROSOFT_GRAPH_CLIENT_ID = os.environ.get("MICROSOFT_GRAPH_CLIENT_ID", "")
MICROSOFT_GRAPH_CLIENT_SECRET = os.environ.get(
    "MICROSOFT_GRAPH_CLIENT_SECRET",
    "",
)
MICROSOFT_GRAPH_SENDER = os.environ.get("MICROSOFT_GRAPH_SENDER", "")
MICROSOFT_GRAPH_TIMEOUT = int(os.environ.get("MICROSOFT_GRAPH_TIMEOUT", "15"))
MICROSOFT_GRAPH_SAVE_TO_SENT_ITEMS = (
    os.environ.get("MICROSOFT_GRAPH_SAVE_TO_SENT_ITEMS", "false").lower()
    in ("1", "true", "yes")
)

CORS_ALLOWED_ORIGINS = env_lista(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173",
)
CSRF_TRUSTED_ORIGINS = env_lista("CSRF_TRUSTED_ORIGINS")

# Endurecimiento activado automáticamente al usar DJANGO_DEBUG=false.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

REST_FRAMEWORK = {
    # Los listados van paginados: el historico de produccion son ~954 lotes y
    # va a seguir creciendo. Sin esto, /lotes/ devolveria la tabla entera.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,

    # Toda la API exige identificarse. Las excepciones se declaran una por una
    # en su vista (login y recuperación de contraseña), nunca al revés: si un
    # endpoint nuevo olvida declarar permisos, queda cerrado en vez de abierto.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "usuarios.authentication.TokenAuthenticationConScope",
        # Sesion tambien, para poder navegar la API desde el navegador
        # estando logueado en /admin/.
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "password_reset_request": "5/hour",
        "password_reset_confirm": "10/hour",
    },
}

validar_entorno_endurecido(
    DJANGO_ENV,
    {
        "DEBUG": DEBUG,
        "SECRET_KEY": SECRET_KEY,
        "ALLOWED_HOSTS": ALLOWED_HOSTS,
        "SECURE_SSL_REDIRECT": SECURE_SSL_REDIRECT,
        "SESSION_COOKIE_SECURE": SESSION_COOKIE_SECURE,
        "CSRF_COOKIE_SECURE": CSRF_COOKIE_SECURE,
        "SECURE_HSTS_SECONDS": SECURE_HSTS_SECONDS,
        "CSRF_TRUSTED_ORIGINS": CSRF_TRUSTED_ORIGINS,
        "DATABASE_CONFIGURED": DATABASE_CONFIGURED,
    },
)
