# Generated by Django 6.0.7 on 2026-07-31 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0002_controlproceso_controlprocesolectura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoPPRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aire_transporte', 'Presión aire transporte fluidizado'), ('aire_secundario', 'Presión aire secundario'), ('roce_valvulas', 'Roce válvulas fluidificadoras'), ('cuerpos_extranos', 'Cuerpos extraños'), ('detector_metales', 'Detector de metales (PCC)')], max_length=30, verbose_name='Tipo de PPRO')),
                ('equipo', models.CharField(blank=True, help_text='E1/E2, Rovema 3/4, etc.', max_length=20, verbose_name='Equipo')),
                ('turno', models.CharField(blank=True, choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], max_length=5, verbose_name='Turno')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('accion_correctiva', models.TextField(blank=True, help_text='Obligatoria si hubo alguna lectura No-OK', verbose_name='Acción correctiva')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos_ppro', to='produccion.lote', verbose_name='Lote')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoreos_ppro', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Monitoreo PPRO',
                'verbose_name_plural': 'Monitoreos PPRO',
                'ordering': ['-fecha', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='PproLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('resultado', models.CharField(choices=[('ok', 'OK'), ('no_ok', 'No OK')], max_length=6, verbose_name='Resultado')),
                ('detalle', models.JSONField(blank=True, default=dict, help_text='Para el detector de metales: {"rechazos": 2, "alarmas": 1}', verbose_name='Detalle')),
                ('monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='inocuidad.monitoreoppro', verbose_name='Monitoreo')),
            ],
            options={
                'verbose_name': 'Lectura PPRO',
                'verbose_name_plural': 'Lecturas PPRO',
                'ordering': ['hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='monitoreoppro',
            constraint=models.UniqueConstraint(fields=('lote', 'tipo', 'equipo', 'fecha', 'turno'), name='monitoreo_ppro_unico_por_turno'),
        ),
        migrations.AddConstraint(
            model_name='pprolectura',
            constraint=models.UniqueConstraint(fields=('monitoreo', 'hora'), name='lectura_ppro_unica_por_hora'),
        ),
    ]
