# Generated by Django 6.0.7 on 2026-08-04 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0010_sembrar_equipos'),
        ('produccion', '0003_alter_lote_kg_producidos'),
        ('usuarios', '0007_alter_perfilusuario_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField()),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepción'), ('estandarizacion', 'Estandarización'), ('descremacion', 'Descremación'), ('evaporacion', 'Evaporación'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envasado', 'Envasado'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=30)),
                ('orden', models.PositiveSmallIntegerField()),
                ('requiere_calidad', models.BooleanField(default=False)),
                ('requiere_inocuidad', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['proceso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('preparacion', 'En preparación'), ('ejecucion', 'En ejecución'), ('pausada', 'Pausada'), ('pendiente_control', 'Pendiente de control'), ('bloqueada', 'Bloqueada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=25)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('termino', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones_proceso', to='maestros.equipo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones_proceso', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones_proceso', to='usuarios.sucursal')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='procesos.etapaproceso')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('estado_anterior', models.CharField(blank=True, max_length=25)),
                ('estado_nuevo', models.CharField(blank=True, max_length=25)),
                ('motivo', models.TextField(blank=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='procesos.ejecucionproceso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField()),
                ('nombre', models.CharField(max_length=160)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', '-version'],
                'constraints': [models.UniqueConstraint(fields=('codigo', 'version'), name='proceso_codigo_version_unica')],
            },
        ),
        migrations.AddField(
            model_name='etapaproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='procesos.proceso'),
        ),
        migrations.CreateModel(
            name='SalidaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturaleza', models.CharField(choices=[('principal', 'Producto principal'), ('coproducto', 'Coproducto'), ('subproducto', 'Subproducto'), ('merma', 'Merma'), ('reproceso', 'Destinado a reproceso')], default='principal', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='procesos.ejecucionproceso')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_proceso', to='produccion.lote')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('mezcla', 'Mezcla'), ('recirculacion', 'Recirculación'), ('reproceso', 'Reproceso')], default='principal', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='procesos.ejecucionproceso')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_proceso', to='produccion.lote')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='entrada_cantidad_positiva'), models.UniqueConstraint(fields=('ejecucion', 'lote', 'tipo'), name='entrada_unica_ejecucion_lote_tipo')],
            },
        ),
        migrations.AddIndex(
            model_name='ejecucionproceso',
            index=models.Index(fields=['sucursal', 'estado', '-creada_en'], name='procesos_ej_sucursa_06bc05_idx'),
        ),
        migrations.AddIndex(
            model_name='ejecucionproceso',
            index=models.Index(fields=['etapa', 'estado'], name='procesos_ej_etapa_i_f07057_idx'),
        ),
        migrations.AddConstraint(
            model_name='ejecucionproceso',
            constraint=models.CheckConstraint(condition=models.Q(('termino__isnull', True), ('inicio__isnull', True), ('termino__gt', models.F('inicio')), _connector='OR'), name='ejecucion_termino_posterior_inicio'),
        ),
        migrations.AddIndex(
            model_name='eventoproceso',
            index=models.Index(fields=['ejecucion', 'fecha_hora'], name='procesos_ev_ejecuci_55113d_idx'),
        ),
        migrations.AddConstraint(
            model_name='etapaproceso',
            constraint=models.UniqueConstraint(fields=('proceso', 'codigo'), name='etapa_codigo_unico_proceso'),
        ),
        migrations.AddConstraint(
            model_name='etapaproceso',
            constraint=models.UniqueConstraint(fields=('proceso', 'orden'), name='etapa_orden_unico_proceso'),
        ),
        migrations.AddConstraint(
            model_name='salidaproceso',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='salida_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='salidaproceso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('naturaleza', 'merma'), _negated=True), ('lote__isnull', True), _connector='OR'), name='salida_merma_sin_lote'),
        ),
    ]
