# Generated by Django 6.0.7 on 2026-08-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0001_initial'),
        ('maestros', '0027_tenant_maestros'),
        ('procesos', '0003_scope_obligatorio_ejecucion'),
        ('produccion', '0006_lote_vale'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionproceso',
            name='vale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecucion', to='estandarizacion.valeestandarizacion', verbose_name='Vale de estandarización'),
        ),
        migrations.AddField(
            model_name='entradaproceso',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_proceso', to='maestros.silo', verbose_name='Silo de origen'),
        ),
        migrations.AddField(
            model_name='salidaproceso',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_proceso', to='maestros.silo', verbose_name='Silo de destino'),
        ),
        migrations.AlterField(
            model_name='entradaproceso',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_proceso', to='produccion.lote'),
        ),
        migrations.AddConstraint(
            model_name='entradaproceso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lote__isnull', False), ('silo__isnull', True)), models.Q(('lote__isnull', True), ('silo__isnull', False)), _connector='OR'), name='entrada_de_un_lote_o_de_un_silo'),
        ),
    ]
