# Generated by Django 6.0.7 on 2026-08-17 20:34

import django.db.models.deletion
import usuarios.tenancy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0028_remove_silo_silo_capacidad_no_negativa_silo_estado_and_more'),
        ('procesos', '0004_ejecucionproceso_vale_entradaproceso_silo_and_more'),
        ('usuarios', '0014_alter_perfilusuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveSmallIntegerField(default=1)),
                ('destino', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_producto', to='procesos.proceso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_proceso', to='maestros.producto')),
                ('sucursal', models.ForeignKey(default=usuarios.tenancy.sucursal_predeterminada_pruebas, on_delete=django.db.models.deletion.PROTECT, related_name='rutas_producto', to='usuarios.sucursal')),
            ],
            options={
                'ordering': ['producto__nombre', 'prioridad', 'proceso__nombre'],
                'indexes': [models.Index(fields=['sucursal', 'producto', 'activa'], name='procesos_ru_sucursa_909c10_idx')],
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'producto', 'proceso'), name='ruta_producto_proceso_unica_planta'), models.CheckConstraint(condition=models.Q(('prioridad__gt', 0)), name='ruta_prioridad_positiva')],
            },
        ),
    ]
