# Generated by Django 6.0.7 on 2026-08-17 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0028_remove_silo_silo_capacidad_no_negativa_silo_estado_and_more'),
        ('procesos', '0005_rutaproducto'),
        ('produccion', '0008_ordenproduccion_lote_orden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaCondensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros_entrada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('litros_precondensado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('flujo_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('densidad_salida', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('solidos_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vacio_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('presion_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('pendiente_calidad', 'Pendiente de Calidad'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=25)),
                ('operacion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corrida_condensacion', to='procesos.ejecucionproceso')),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condensaciones_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condensaciones_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas_condensacion', to='produccion.lote')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas_condensacion', to='produccion.ordenproduccion')),
                ('silo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condensaciones_destino', to='maestros.silo')),
                ('silo_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condensaciones_origen', to='maestros.silo')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('litros_entrada__gt', 0)), name='condensacion_entrada_positiva'), models.CheckConstraint(condition=models.Q(('litros_precondensado__isnull', True), ('litros_precondensado__gt', 0), _connector='OR'), name='condensacion_salida_positiva')],
            },
        ),
    ]
