# Generated by Django 6.0.7 on 2026-08-17 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_corridacondensacion'),
        ('produccion', '0009_registroenvase_palletproducto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaproceso',
            name='tipo',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('estandarizacion', 'Estandarización'), ('descremacion', 'Descremación'), ('evaporacion', 'Evaporación'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envasado', 'Envasado'), ('mantequilla', 'Mantequilla'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.CreateModel(
            name='CorridaMantequilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_crema', models.DecimalField(decimal_places=3, max_digits=14)),
                ('kg_mantequilla', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('kg_suero', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('kg_merma', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('controles', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('pendiente_calidad', 'Pendiente de Calidad'), ('cerrada', 'Cerrada')], db_index=True, default='borrador', max_length=25)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corrida_mantequilla', to='procesos.ejecucionproceso')),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantequillas_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantequillas_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('lote_crema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_mantequilla', to='produccion.lote')),
                ('lote_mantequilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas_mantequilla', to='produccion.lote')),
                ('lote_suero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridas_como_suero_mantequilla', to='produccion.lote')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas_mantequilla', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kg_crema__gt', 0)), name='mantequilla_crema_positiva'), models.CheckConstraint(condition=models.Q(('kg_suero__gte', 0)), name='mantequilla_suero_no_negativo'), models.CheckConstraint(condition=models.Q(('kg_merma__gte', 0)), name='mantequilla_merma_no_negativa')],
            },
        ),
    ]
