# Generated by Django 6.0.7 on 2026-08-25 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0031_sembrar_siglas'),
        ('procesos', '0007_alter_etapaproceso_tipo_corridamantequilla'),
        ('produccion', '0013_correccionlote'),
        ('recepcion', '0025_alter_movimientosilo_origen_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaDescremacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros_entrada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('grasa_entrada', models.DecimalField(decimal_places=3, max_digits=6)),
                ('sng_entrada', models.DecimalField(decimal_places=3, max_digits=6)),
                ('litros_descremada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('grasa_descremada', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('litros_crema', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('grasa_crema', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('controles', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], db_index=True, default='borrador', max_length=20)),
                ('operacion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('analisis_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descremaciones', to='recepcion.analisissilo')),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corrida_descremacion', to='procesos.ejecucionproceso')),
                ('estanque_crema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crema_descremaciones', to='maestros.silo')),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descremaciones_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descremaciones_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridas_descremacion', to='produccion.ordenproduccion')),
                ('silo_descremada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descremaciones_salida', to='maestros.silo')),
                ('silo_entera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descremaciones_origen', to='maestros.silo')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('litros_entrada__gt', 0)), name='descremacion_entrada_positiva'), models.CheckConstraint(condition=models.Q(('litros_descremada__isnull', True), ('litros_descremada__gt', 0), _connector='OR'), name='descremacion_descremada_positiva'), models.CheckConstraint(condition=models.Q(('litros_crema__isnull', True), ('litros_crema__gt', 0), _connector='OR'), name='descremacion_crema_positiva')],
            },
        ),
    ]
