# Generated by Django 6.0.7 on 2026-08-31 19:56

from django.db import migrations, models


def clasificar_salidas_existentes(apps, schema_editor):
    Salida = apps.get_model("procesos", "SalidaProceso")
    for salida in Salida.objects.select_related("ejecucion__etapa").iterator():
        tipo = salida.ejecucion.etapa.tipo
        if salida.naturaleza == "merma":
            salida.clasificacion, salida.destino = "merma", "otro"
        elif tipo in {"secado", "mantequilla"}:
            salida.clasificacion, salida.destino = "granel", "envasado"
        elif tipo == "envasado":
            salida.clasificacion, salida.destino = "terminado", "inventario"
        elif tipo == "estandarizacion":
            salida.clasificacion, salida.destino = "intermedio", "siguiente_proceso"
        elif salida.naturaleza in {"coproducto", "subproducto"}:
            salida.clasificacion, salida.destino = "subproducto", "pendiente"
        else:
            salida.clasificacion, salida.destino = "intermedio", "pendiente"
        salida.save(update_fields=["clasificacion", "destino"])


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_entradaproceso_salida_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproceso',
            name='motivo',
            field=models.CharField(blank=True, help_text='Obligatorio cuando la entrada corresponde a reproceso.', max_length=250),
        ),
        migrations.AddField(
            model_name='salidaproceso',
            name='clasificacion',
            field=models.CharField(choices=[('intermedio', 'Producto intermedio'), ('granel', 'Producto a granel'), ('subproducto', 'Subproducto'), ('terminado', 'Producto terminado'), ('merma', 'Merma')], db_index=True, default='intermedio', max_length=20),
        ),
        migrations.AddField(
            model_name='salidaproceso',
            name='destino',
            field=models.CharField(choices=[('pendiente', 'Destino por definir'), ('siguiente_proceso', 'Siguiente proceso'), ('estandarizacion', 'Estandarización'), ('envasado', 'Envasado'), ('inventario', 'Inventario'), ('despacho_directo', 'Despacho directo'), ('reproceso', 'Reproceso'), ('otro', 'Otro destino controlado')], db_index=True, default='pendiente', max_length=25),
        ),
        migrations.RunPython(clasificar_salidas_existentes, migrations.RunPython.noop),
    ]
