# Generated by Django 6.0.7 on 2026-09-02 15:26

from django.conf import settings
from django.db import migrations, models


def verificar_sin_ocupaciones_duplicadas(apps, schema_editor):
    Ejecucion = apps.get_model("procesos", "EjecucionProceso")
    duplicados = (
        Ejecucion.objects.filter(
            equipo__isnull=False,
            estado__in=["preparacion", "ejecucion", "pausada", "bloqueada"],
        )
        .values("equipo_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    if duplicados.exists():
        equipos = ", ".join(str(item["equipo_id"]) for item in duplicados)
        raise RuntimeError(
            "No se puede proteger la ocupación: hay ejecuciones simultáneas "
            f"en los equipos {equipos}. Ciérralas o cancélalas antes de migrar."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0007_valeestandarizacion_analisis_crema_and_more'),
        ('maestros', '0031_sembrar_siglas'),
        ('procesos', '0014_completar_rutas_productivas'),
        ('usuarios', '0016_alter_perfilusuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            verificar_sin_ocupaciones_duplicadas,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='ejecucionproceso',
            constraint=models.UniqueConstraint(condition=models.Q(('equipo__isnull', False), ('estado__in', ['preparacion', 'ejecucion', 'pausada', 'bloqueada'])), fields=('equipo',), name='ejecucion_equipo_ocupado_unico'),
        ),
    ]
