# Generated by Django 6.0.7 on 2026-09-02 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def vincular_secados_historicos(apps, schema_editor):
    CorridaSecado = apps.get_model("procesos", "CorridaSecado")
    Ejecucion = apps.get_model("procesos", "EjecucionProceso")
    Lote = apps.get_model("produccion", "Lote")

    ejecuciones = Ejecucion.objects.filter(etapa__tipo="secado")
    for ejecucion in ejecuciones.iterator():
        lote = Lote.objects.filter(ejecucion_id=ejecucion.pk).order_by("pk").first()
        if lote is None:
            continue
        CorridaSecado.objects.get_or_create(
            ejecucion_id=ejecucion.pk,
            defaults={
                "lote_id": lote.pk,
                "orden_id": lote.orden_id,
                "kg_polvo": lote.kg_producidos,
                "finalizada_en": ejecucion.termino,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0015_impedir_doble_ocupacion_equipo'),
        ('produccion', '0014_pallet_kg_maximo_500'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaSecado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_alimentacion', models.DecimalField(blank=True, decimal_places=3, help_text='Masa medida de precondensado alimentada a la torre.', max_digits=14, null=True)),
                ('solidos_entrada_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('kg_polvo', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('kg_finos', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('kg_merma', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('controles', models.JSONField(blank=True, default=dict)),
                ('operacion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corrida_secado', to='procesos.ejecucionproceso')),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secados_finalizados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corrida_secado', to='produccion.lote')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridas_secado', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kg_alimentacion__isnull', True), ('kg_alimentacion__gt', 0), _connector='OR'), name='secado_alimentacion_positiva'), models.CheckConstraint(condition=models.Q(('solidos_entrada_pct__isnull', True), models.Q(('solidos_entrada_pct__gt', 0), ('solidos_entrada_pct__lte', 100)), _connector='OR'), name='secado_solidos_entrada_validos'), models.CheckConstraint(condition=models.Q(('kg_polvo__isnull', True), ('kg_polvo__gt', 0), _connector='OR'), name='secado_polvo_positivo'), models.CheckConstraint(condition=models.Q(('kg_finos__gte', 0), ('kg_merma__gte', 0)), name='secado_finos_merma_no_negativos')],
            },
        ),
        migrations.RunPython(vincular_secados_historicos, migrations.RunPython.noop),
    ]
