# Generated by Django 6.0.7 on 2026-09-03 14:42

import django.db.models.deletion
from django.db import migrations, models


def estructurar_destinos_y_trazabilidad(apps, schema_editor):
    Ruta = apps.get_model('procesos', 'RutaProducto')
    Ejecucion = apps.get_model('procesos', 'EjecucionProceso')
    Salida = apps.get_model('procesos', 'SalidaProceso')
    Lote = apps.get_model('produccion', 'Lote')

    for ruta in Ruta.objects.all().iterator():
        texto = (ruta.destino or '').strip().lower()
        if 'despacho' in texto:
            destino = 'despacho_directo'
        elif 'inventario' in texto:
            destino = 'inventario'
        elif 'envas' in texto:
            destino = 'envasado'
        else:
            destino = 'siguiente_proceso'
        Ruta.objects.filter(pk=ruta.pk).update(destino_final=destino)

    rutas = {
        (ruta.sucursal_id, ruta.producto_id, ruta.proceso_id): ruta.pk
        for ruta in Ruta.objects.filter(activa=True).order_by('prioridad', 'pk')
    }
    for ejecucion in Ejecucion.objects.select_related('etapa').all().iterator():
        lote = Lote.objects.filter(ejecucion_id=ejecucion.pk).first()
        if lote is None:
            continue
        ruta_id = rutas.get((ejecucion.sucursal_id, lote.producto_id, ejecucion.etapa.proceso_id))
        if ruta_id:
            Ejecucion.objects.filter(pk=ejecucion.pk).update(ruta_producto_id=ruta_id)

    for salida in Salida.objects.select_related('lote', 'ejecucion').all().iterator():
        producto_id = salida.lote.producto_id if salida.lote_id else None
        Salida.objects.filter(pk=salida.pk).update(
            producto_id=producto_id,
            ruta_producto_id=salida.ejecucion.ruta_producto_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0032_especificacion_tipo_analisis'),
        ('procesos', '0016_corrida_secado'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridadescremacion',
            name='destino_crema',
            field=models.CharField(choices=[('pendiente', 'Destino por definir'), ('estandarizacion', 'Estandarizacion'), ('siguiente_proceso', 'Siguiente proceso'), ('despacho_directo', 'Despacho directo')], default='pendiente', max_length=25),
        ),
        migrations.AddField(
            model_name='corridadescremacion',
            name='destino_descremada',
            field=models.CharField(choices=[('pendiente', 'Destino por definir'), ('estandarizacion', 'Estandarizacion'), ('siguiente_proceso', 'Siguiente proceso'), ('despacho_directo', 'Despacho directo')], default='pendiente', max_length=25),
        ),
        migrations.AddField(
            model_name='corridadescremacion',
            name='ruta_crema',
            field=models.ForeignKey(blank=True, help_text='Ruta elegida independientemente para la crema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridas_descremacion_crema', to='procesos.rutaproducto'),
        ),
        migrations.AddField(
            model_name='corridadescremacion',
            name='ruta_descremada',
            field=models.ForeignKey(blank=True, help_text='Ruta elegida independientemente para la leche descremada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridas_descremacion_descremada', to='procesos.rutaproducto'),
        ),
        migrations.AddField(
            model_name='ejecucionproceso',
            name='ruta_producto',
            field=models.ForeignKey(blank=True, help_text='Ruta productiva elegida al crear la ejecucion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='procesos.rutaproducto'),
        ),
        migrations.AddField(
            model_name='rutaproducto',
            name='destino_final',
            field=models.CharField(choices=[('siguiente_proceso', 'Siguiente proceso'), ('envasado', 'Envasado'), ('despacho_directo', 'Despacho directo'), ('inventario', 'Inventario')], db_index=True, default='siguiente_proceso', max_length=25),
        ),
        migrations.AddField(
            model_name='salidaproceso',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Identidad explicita del material resultante.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_proceso', to='maestros.producto'),
        ),
        migrations.AddField(
            model_name='salidaproceso',
            name='ruta_producto',
            field=models.ForeignKey(blank=True, help_text='Ruta elegida para la continuidad de esta salida.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_proceso', to='procesos.rutaproducto'),
        ),
        migrations.RunPython(
            estructurar_destinos_y_trazabilidad,
            migrations.RunPython.noop,
        ),
    ]
