# Generated by Django 6.0.7 on 2026-09-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_unidadrework_movimientorework_and_more'),
        ('maestros', '0038_formatoenvasado_tipo_unidad_logistica_and_more'),
        ('procesos', '0020_reparar_lotes_suero_mantequilla'),
        ('produccion', '0016_remove_palletproducto_pallet_kg_maximo_500_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entradaproceso',
            name='entrada_de_un_lote_o_de_un_silo',
        ),
        migrations.AddField(
            model_name='entradaproceso',
            name='lote_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_proceso', to='inventario.loteinventario', verbose_name='Lote externo de origen'),
        ),
        migrations.AddField(
            model_name='rutaproducto',
            name='insumo_origen',
            field=models.ForeignKey(blank=True, help_text='Materia prima externa que puede iniciar esta ruta. Se deja vacio cuando la ruta nace desde un silo o una salida interna.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutas_productivas', to='inventario.insumo'),
        ),
        migrations.AddConstraint(
            model_name='entradaproceso',
            constraint=models.UniqueConstraint(fields=('ejecucion', 'lote_inventario', 'tipo'), name='entrada_unica_ejecucion_lote_inv_tipo'),
        ),
        migrations.AddConstraint(
            model_name='entradaproceso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lote__isnull', False), ('lote_inventario__isnull', True), ('silo__isnull', True)), models.Q(('lote__isnull', True), ('lote_inventario__isnull', True), ('silo__isnull', False)), models.Q(('lote__isnull', True), ('lote_inventario__isnull', False), ('silo__isnull', True)), _connector='OR'), name='entrada_con_un_solo_origen'),
        ),
    ]
