# Generated by Django 6.0.7 on 2026-08-06 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0016_frecuencia_de_los_checklists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('proveedor', models.CharField(max_length=160)),
                ('predio', models.CharField(max_length=160)),
                ('sala', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('no_cargada', 'No cargada')], db_index=True, default='pendiente', max_length=20)),
                ('llegada', models.DateTimeField(blank=True, null=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_hora', models.DateTimeField()),
                ('litros_medidos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alcohol', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme')], max_length=20)),
                ('codigo_muestra', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('cargada', 'Cargada'), ('rechazada', 'No cargada')], db_index=True, default='registrada', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recolecciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('parada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recoleccion', to='recoleccion.paradaruta')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='CargaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('modulo', models.CharField(max_length=40)),
                ('estanque_origen', models.CharField(blank=True, max_length=60)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cargada_en', models.DateTimeField(auto_now_add=True)),
                ('recoleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='recoleccion.recoleccion')),
            ],
            options={
                'ordering': ['recoleccion', 'modulo', 'estanque_origen'],
            },
        ),
        migrations.CreateModel(
            name='RutaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='programada', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutas_recoleccion', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_recoleccion_creadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_recoleccion', to='maestros.vehiculo')),
            ],
            options={
                'ordering': ['-fecha', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='recoleccion.rutarecoleccion'),
        ),
        migrations.AddConstraint(
            model_name='recoleccion',
            constraint=models.CheckConstraint(condition=models.Q(('litros_medidos__gt', 0)), name='recoleccion_litros_positivos'),
        ),
        migrations.AddConstraint(
            model_name='recoleccion',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_muestra', ''), _negated=True), fields=('codigo_muestra',), name='muestra_recoleccion_unica'),
        ),
        migrations.AddConstraint(
            model_name='cargamodulo',
            constraint=models.CheckConstraint(condition=models.Q(('litros__gt', 0)), name='carga_modulo_litros_positivos'),
        ),
        migrations.AddConstraint(
            model_name='cargamodulo',
            constraint=models.UniqueConstraint(fields=('recoleccion', 'modulo', 'estanque_origen'), name='carga_unica_modulo_estanque_recoleccion'),
        ),
        migrations.AddIndex(
            model_name='rutarecoleccion',
            index=models.Index(fields=['fecha', 'estado'], name='recoleccion_fecha_557014_idx'),
        ),
        migrations.AddConstraint(
            model_name='paradaruta',
            constraint=models.UniqueConstraint(fields=('ruta', 'orden'), name='parada_orden_unico_por_ruta'),
        ),
    ]
