# Generated by Django 6.0.7 on 2026-08-05 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0026_componentes_nulos_distintos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorLeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('motivo_bloqueo', models.TextField(blank=True, verbose_name='Motivo del bloqueo')),
            ],
            options={
                'verbose_name': 'Proveedor de leche',
                'verbose_name_plural': 'Proveedores de leche',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('capacidad_l', models.DecimalField(blank=True, decimal_places=2, help_text='En litros', max_digits=12, null=True, verbose_name='Capacidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='maestros.vehiculo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['vehiculo', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, verbose_name='Código')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre')),
                ('comuna', models.CharField(blank=True, max_length=120, verbose_name='Comuna')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predios', to='recoleccion.proveedorleche')),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'ordering': ['proveedor', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código de recolección')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_ruta', 'En ruta'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recolecciones', to='maestros.vehiculo')),
                ('carro', models.ForeignKey(blank=True, help_text='El acoplado, si lo lleva.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recolecciones_carro', to='maestros.vehiculo')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recolecciones', to='recoleccion.conductor')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recolecciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CargaPredio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Litros')),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='En °C. El objetivo en predio es ~4 °C.', max_digits=5, verbose_name='Temperatura')),
                ('alcohol', models.CharField(choices=[('negativa', 'Negativa (conforme)'), ('positiva', 'Positiva (no conforme)')], max_length=10, verbose_name='Prueba de alcohol')),
                ('visual', models.CharField(choices=[('conforme', 'Conforme'), ('no_conforme', 'No conforme')], default='conforme', max_length=15, verbose_name='Evaluación visual')),
                ('muestra_tomada', models.BooleanField(default=False, verbose_name='Muestra tomada')),
                ('cargada', models.BooleanField(default=True, help_text='Falso cuando la leche se quedó en el predio.', verbose_name='Se cargó al camión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(blank=True, help_text='En qué módulo se cargó. Vacío si no se cargó.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='recoleccion.modulo')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='recoleccion.predio')),
                ('recoleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='recoleccion.recoleccion')),
            ],
            options={
                'verbose_name': 'Carga en predio',
                'verbose_name_plural': 'Cargas en predio',
                'ordering': ['recoleccion', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'numero'), name='modulo_numero_unico_vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='predio',
            constraint=models.UniqueConstraint(fields=('proveedor', 'codigo'), name='predio_codigo_unico_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='cargapredio',
            constraint=models.CheckConstraint(condition=models.Q(('litros__gt', 0)), name='carga_litros_positivos'),
        ),
        migrations.AddConstraint(
            model_name='cargapredio',
            constraint=models.CheckConstraint(condition=models.Q(('cargada', False), ('modulo__isnull', False), _connector='OR'), name='carga_cargada_indica_modulo'),
        ),
    ]
