# Generated by Django 6.0.7 on 2026-07-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(help_text='Correlativo de planta. No es único: se repite entre productos y días', max_length=60, verbose_name='Código de lote')),
                ('op', models.CharField(blank=True, help_text='Orden de producción, si existe', max_length=60, verbose_name='OP')),
                ('fecha', models.DateField(verbose_name='Fecha de producción')),
                ('linea', models.CharField(blank=True, choices=[('E1', 'Línea 1 · E1'), ('E2', 'Línea 2 · E2')], max_length=5, verbose_name='Línea')),
                ('turno', models.CharField(blank=True, choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], max_length=5, verbose_name='Turno')),
                ('kg_producidos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kilos producidos')),
                ('bultos', models.PositiveIntegerField(blank=True, help_text='Bolsas o cajas', null=True, verbose_name='Bultos')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_termino', models.TimeField(blank=True, null=True, verbose_name='Hora de término')),
                ('vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('producido', 'Producido'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='maestros.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lote de producción',
                'verbose_name_plural': 'Lotes de producción',
                'ordering': ['-fecha', 'codigo_lote'],
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del análisis')),
                ('muestra', models.CharField(blank=True, help_text='Identificador de la muestra o del despacho analizado', max_length=120, verbose_name='Muestra')),
                ('valores', models.JSONField(default=dict, help_text='{"humedad": 3.2, "mg": 26.5, ...}', verbose_name='Parámetros medidos')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('especificacion', models.ForeignKey(blank=True, help_text='Versión usada al evaluar. Se congela para auditoría', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analisis', to='maestros.especificacion', verbose_name='Especificación aplicada')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='produccion.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Análisis de calidad',
                'verbose_name_plural': 'Análisis de calidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('codigo_lote', 'producto', 'fecha'), name='lote_clave_natural_unica'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(condition=models.Q(('kg_producidos__gte', 0)), name='lote_kg_no_negativos'),
        ),
    ]
