# Generated by Django 6.0.7 on 2026-07-31 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(choices=[('VEB', 'Evaporador VEB'), ('SCH2', 'Evaporador Scheffers 2'), ('SCH3', 'Evaporador Scheffers 3'), ('E1', 'Torre de secado Egron 1'), ('E2', 'Torre de secado Egron 2')], max_length=10, verbose_name='Equipo')),
                ('turno', models.CharField(blank=True, choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], max_length=5, verbose_name='Turno')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_arranque', models.TimeField(blank=True, null=True, verbose_name='Hora de arranque')),
                ('hora_inicio_produccion', models.TimeField(blank=True, null=True, verbose_name='Inicio de producción')),
                ('hora_termino_produccion', models.TimeField(blank=True, null=True, verbose_name='Término de producción')),
                ('pcc1_temp_min', models.DecimalField(blank=True, decimal_places=1, help_text='En °C. Una lectura por debajo incumple el PCC', max_digits=5, null=True, verbose_name='PCC1 · Temperatura mínima')),
                ('pcc1_caudal_max', models.DecimalField(blank=True, decimal_places=1, help_text='En kg/h. Una lectura por encima incumple el PCC', max_digits=10, null=True, verbose_name='PCC1 · Caudal máximo')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_proceso', to='produccion.lote', verbose_name='Lote')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_proceso', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Control de proceso',
                'verbose_name_plural': 'Controles de proceso',
                'ordering': ['-fecha', 'equipo'],
            },
        ),
        migrations.CreateModel(
            name='ControlProcesoLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('valores', models.JSONField(default=dict, help_text='{"flujo_entrada": 13500, "densidad": 1020, "t_dsi": 82.1, ...}', verbose_name='Valores medidos')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='produccion.controlproceso', verbose_name='Control de proceso')),
            ],
            options={
                'verbose_name': 'Lectura de control de proceso',
                'verbose_name_plural': 'Lecturas de control de proceso',
                'ordering': ['hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='controlproceso',
            constraint=models.UniqueConstraint(fields=('lote', 'equipo', 'fecha', 'turno'), name='control_proceso_unico_por_lote_equipo_fecha_turno'),
        ),
        migrations.AddConstraint(
            model_name='controlprocesolectura',
            constraint=models.UniqueConstraint(fields=('control', 'hora'), name='lectura_control_unica_por_hora'),
        ),
    ]
