# Generated by Django 6.0.7 on 2026-07-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_controlproceso_controlprocesolectura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='kg_producidos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se declaran al cerrar la producción', max_digits=12, null=True, verbose_name='Kilos producidos'),
        ),
    ]
