# Generated by Django 6.0.7 on 2026-08-12 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0001_initial'),
        ('produccion', '0005_tenant_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='vale',
            field=models.ForeignKey(blank=True, help_text='De qué vale salió la leche de este lote. Quien consume el silo es el vale; el lote declara a qué producto va esa leche.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estandarizacion.valeestandarizacion', verbose_name='Vale de estandarización'),
        ),
    ]
