# Generated by Django 6.0.7 on 2026-08-17 20:22

import django.db.models.deletion
import usuarios.tenancy
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0027_tenant_maestros'),
        ('planificacion', '0004_semanaplan_cancelada_en_semanaplan_cancelada_por_and_more'),
        ('produccion', '0007_lote_equipo_ejecucion'),
        ('usuarios', '0014_alter_perfilusuario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unidad', models.CharField(choices=[('l', 'Litros'), ('kg', 'Kilogramos')], max_length=5)),
                ('linea', models.CharField(blank=True, max_length=60)),
                ('destino', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('en_proceso', 'En proceso'), ('pendiente_calidad', 'Pendiente de Calidad'), ('liberada', 'Liberada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=25)),
                ('observacion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='maestros.equipo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='maestros.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion_responsable', to=settings.AUTH_USER_MODEL)),
                ('semana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='planificacion.semanaplan')),
                ('sucursal', models.ForeignKey(default=usuarios.tenancy.sucursal_predeterminada_pruebas, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='usuarios.sucursal')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='orden',
            field=models.ForeignKey(blank=True, help_text='Orden estructurada. `op` se conserva para datos históricos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produccion.ordenproduccion'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='orden_codigo_unico_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_planificada__gt', 0)), name='orden_cantidad_planificada_positiva'),
        ),
    ]
