# Generated by Django 6.0.7 on 2026-08-17 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0028_remove_silo_silo_capacidad_no_negativa_silo_estado_and_more'),
        ('produccion', '0008_ordenproduccion_lote_orden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidades', models.PositiveIntegerField()),
                ('kg_envasados', models.DecimalField(decimal_places=3, max_digits=14)),
                ('controles', models.JSONField(blank=True, default=dict)),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField()),
                ('observacion', models.TextField(blank=True)),
                ('operacion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_envase', to='maestros.equipo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_envase', to='produccion.lote')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_envase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PalletProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('unidades', models.PositiveIntegerField()),
                ('kg_neto', models.DecimalField(decimal_places=3, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente_calidad', 'Pendiente de Calidad'), ('bloqueado', 'Bloqueado'), ('liberado', 'Liberado'), ('en_inventario', 'En inventario'), ('despachado', 'Despachado'), ('anulado', 'Anulado')], db_index=True, default='pendiente_calidad', max_length=25)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('envase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='produccion.registroenvase')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='registroenvase',
            constraint=models.CheckConstraint(condition=models.Q(('formato_kg__gt', 0)), name='envase_formato_positivo'),
        ),
        migrations.AddConstraint(
            model_name='registroenvase',
            constraint=models.CheckConstraint(condition=models.Q(('unidades__gt', 0)), name='envase_unidades_positivas'),
        ),
        migrations.AddConstraint(
            model_name='registroenvase',
            constraint=models.CheckConstraint(condition=models.Q(('kg_envasados__gt', 0)), name='envase_kg_positivos'),
        ),
        migrations.AddConstraint(
            model_name='registroenvase',
            constraint=models.CheckConstraint(condition=models.Q(('termino__gt', models.F('inicio'))), name='envase_termino_posterior_inicio'),
        ),
        migrations.AddConstraint(
            model_name='palletproducto',
            constraint=models.CheckConstraint(condition=models.Q(('unidades__gt', 0)), name='pallet_unidades_positivas'),
        ),
        migrations.AddConstraint(
            model_name='palletproducto',
            constraint=models.CheckConstraint(condition=models.Q(('kg_neto__gt', 0)), name='pallet_kg_positivos'),
        ),
    ]
