# Generated by Django 6.0.7 on 2026-08-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0003_procedencia_del_analisis'),
        ('maestros', '0031_sembrar_siglas'),
        ('procesos', '0007_alter_etapaproceso_tipo_corridamantequilla'),
        ('produccion', '0009_registroenvase_palletproducto_and_more'),
        ('usuarios', '0015_alter_perfilusuario_alcance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lote',
            name='lote_clave_natural_unica',
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo_lote'), name='lote_codigo_unico_sucursal'),
        ),
    ]
