# Generated by Django 6.0.7 on 2026-08-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_lote_codigo_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='lote_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='continuaciones', to='produccion.lote', verbose_name='Continúa a'),
        ),
        migrations.AddField(
            model_name='lote',
            name='motivo_corte',
            field=models.TextField(blank=True, verbose_name='Motivo del corte'),
        ),
    ]
