# Generated by Django 6.0.7 on 2026-08-25 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def conservar_codigo_existente(apps, schema_editor):
    Lote = apps.get_model("produccion", "Lote")
    for lote in Lote.objects.only("id", "codigo_lote").iterator():
        Lote.objects.filter(pk=lote.pk).update(
            codigo_lote_propuesto=lote.codigo_lote
        )


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0031_sembrar_siglas'),
        ('produccion', '0011_lote_corte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='abierto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='abierto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borradores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='codigo_lote_propuesto',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código definitivo propuesto'),
        ),
        migrations.RunPython(conservar_codigo_existente, migrations.RunPython.noop),
        migrations.AddField(
            model_name='lote',
            name='litros_estandarizados_borrador',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Litros estandarizados por confirmar'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('producido', 'Producido'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='en_proceso', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='maestros.producto', verbose_name='Producto'),
        ),
    ]
