# Generated by Django 6.0.7 on 2026-08-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_lote_abierto_en_lote_abierto_por_lote_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('cambios', models.JSONField(default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='produccion.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_lote_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
            },
        ),
    ]
