# Generated by Django 6.0.7 on 2026-09-04 14:11

import django.db.models.deletion
from django.db import migrations, models


def vincular_formatos_historicos(apps, schema_editor):
    Registro = apps.get_model("produccion", "RegistroEnvase")
    Formato = apps.get_model("maestros", "FormatoEnvasado")
    formatos = {
        (formato.producto_id, formato.kg_neto): formato.pk
        for formato in Formato.objects.all()
    }
    for registro in Registro.objects.filter(formato__isnull=True).only(
        "id", "lote_id", "formato_kg"
    ).select_related("lote"):
        formato_id = formatos.get((registro.lote.producto_id, registro.formato_kg))
        if formato_id:
            Registro.objects.filter(pk=registro.pk).update(formato_id=formato_id)


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0037_formatoenvasado'),
        ('produccion', '0014_pallet_kg_maximo_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenvase',
            name='formato',
            field=models.ForeignKey(blank=True, help_text='Configuración usada; nulo solamente para registros históricos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_envase', to='maestros.formatoenvasado'),
        ),
        migrations.RunPython(
            vincular_formatos_historicos, migrations.RunPython.noop
        ),
    ]
