# Generated by Django 6.0.7 on 2026-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_registroenvase_formato'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='palletproducto',
            name='pallet_kg_maximo_500',
        ),
        migrations.AddField(
            model_name='palletproducto',
            name='tipo_unidad_logistica',
            field=models.CharField(choices=[('pallet', 'Pallet'), ('big_bag', 'Big Bag')], default='pallet', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='palletproducto',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_unidad_logistica', 'big_bag'), ('kg_neto__lte', 500), _connector='OR'), name='unidad_logistica_peso_valido'),
        ),
    ]
