# Generated by Django 6.0.7 on 2026-07-31 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0006_receta_recetacomponente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('formato', models.CharField(blank=True, choices=[('SH2', 'Scheffers 2'), ('SH3', 'Scheffers 3'), ('VEB', 'VEB')], max_length=5, verbose_name='Formato')),
                ('categoria', models.CharField(choices=[('prec_nestle', 'Precondensado Nestlé'), ('prec_ccaa', 'Precondensado CCAA'), ('secado_ccaa', 'Secado CCAA'), ('secado_nestle', 'Secado Nestlé'), ('secado_colun', 'Secado Colún')], help_text='A qué fila de CONSUMO del balance suma', max_length=20, verbose_name='Categoría de consumo')),
                ('rendimiento_lh', models.DecimalField(decimal_places=2, help_text='Litros de leche por hora de corrida (columna C de la hoja BD)', max_digits=12, verbose_name='Rendimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('mandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_produccion', to='maestros.mandante', verbose_name='Mandante')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_produccion', to='maestros.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Código de producción',
                'verbose_name_plural': 'Códigos de producción',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SemanaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. W7', max_length=10, verbose_name='Código')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Lunes de la semana')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=10, verbose_name='Estado')),
                ('publicada_en', models.DateTimeField(blank=True, null=True, verbose_name='Publicada en')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('publicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semanas_publicadas', to=settings.AUTH_USER_MODEL, verbose_name='Publicada por')),
            ],
            options={
                'verbose_name': 'Semana de planificación',
                'verbose_name_plural': 'Semanas de planificación',
                'ordering': ['-anio', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloquePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(choices=[('carga_precondensado', 'Carga de precondensado'), ('scheffers2', 'Evaporador Scheffers 2'), ('scheffers3', 'Evaporador Scheffers 3'), ('veb', 'Evaporador VEB'), ('linea1', 'Línea 1'), ('linea2', 'Línea 2'), ('linea_mantequilla', 'Línea de mantequilla')], max_length=25, verbose_name='Equipo')),
                ('dia', models.PositiveSmallIntegerField(help_text='0 = lunes … 6 = domingo', verbose_name='Día')),
                ('hora_inicio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Hora de inicio')),
                ('hora_fin', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Hora de término')),
                ('tipo', models.CharField(choices=[('produccion', 'Producción'), ('estado', 'Estado del equipo')], max_length=12, verbose_name='Tipo')),
                ('estado_equipo', models.CharField(blank=True, choices=[('A', 'Aseo'), ('P', 'PNP'), ('M', 'Mantenimiento'), ('X', 'Preparación'), ('AP', 'Atraso de partida')], max_length=3, verbose_name='Estado del equipo')),
                ('cantidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kilos objetivo')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bloques', to='planificacion.codigoproduccion', verbose_name='Código de producción')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='planificacion.semanaplan', verbose_name='Semana')),
            ],
            options={
                'verbose_name': 'Bloque de programa',
                'verbose_name_plural': 'Bloques de programa',
                'ordering': ['dia', 'equipo', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BalanceDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(help_text='0 = lunes … 6 = domingo', verbose_name='Día')),
                ('stock_inicial', models.DecimalField(blank=True, decimal_places=2, help_text='Solo el del primer día; los demás se arrastran', max_digits=12, null=True, verbose_name='Stock a las 8 AM')),
                ('recepcion_ccaa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Recepción CCAA')),
                ('recepcion_nestle', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Recepción Nestlé')),
                ('recepcion_punion', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Recepción P. Unión')),
                ('trasvasije', models.DecimalField(decimal_places=2, default=0, help_text='Traspaso puntual. No sale de ningún bloque: se teclea', max_digits=12, verbose_name='Trasvasije')),
                ('crema_disponible_ton', models.DecimalField(blank=True, decimal_places=2, help_text='En toneladas', max_digits=10, null=True, verbose_name='Crema disponible')),
                ('ajustes', models.JSONField(blank=True, default=dict, help_text='Correcciones puntuales en litros: {"ccaa": -5800, "nestle": 40040}', verbose_name='Ajustes por origen')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='planificacion.semanaplan', verbose_name='Semana')),
            ],
            options={
                'verbose_name': 'Balance de leche del día',
                'verbose_name_plural': 'Balances de leche',
                'ordering': ['semana', 'dia'],
            },
        ),
        migrations.AddConstraint(
            model_name='codigoproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('rendimiento_lh__gte', 0)), name='codigo_produccion_rendimiento_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='semanaplan',
            constraint=models.UniqueConstraint(fields=('codigo', 'anio'), name='semana_plan_unica_por_anio'),
        ),
        migrations.AddConstraint(
            model_name='bloqueplan',
            constraint=models.CheckConstraint(condition=models.Q(('dia__gte', 0), ('dia__lte', 6)), name='bloque_plan_dia_de_la_semana'),
        ),
        migrations.AddConstraint(
            model_name='bloqueplan',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__gte', 0), ('hora_inicio__lte', 24)), name='bloque_plan_hora_inicio_valida'),
        ),
        migrations.AddConstraint(
            model_name='bloqueplan',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gte', 0), ('hora_fin__lte', 24)), name='bloque_plan_hora_fin_valida'),
        ),
        migrations.AddConstraint(
            model_name='bloqueplan',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='bloque_plan_termina_despues_de_empezar'),
        ),
        migrations.AddConstraint(
            model_name='balancedia',
            constraint=models.UniqueConstraint(fields=('semana', 'dia'), name='balance_dia_unico_por_semana'),
        ),
        migrations.AddConstraint(
            model_name='balancedia',
            constraint=models.CheckConstraint(condition=models.Q(('dia__gte', 0), ('dia__lte', 6)), name='balance_dia_de_la_semana'),
        ),
    ]
