# Generated by Django 6.0.7 on 2026-08-06 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0026_componentes_nulos_distintos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeEstandarizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código de vale')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('rc_objetivo', models.DecimalField(decimal_places=4, help_text='Materia grasa dividida por sólidos no grasos.', max_digits=6, verbose_name='RC objetivo')),
                ('volumen', models.DecimalField(decimal_places=2, help_text='En litros', max_digits=12, verbose_name='Volumen a preparar')),
                ('entera_grasa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Grasa de la entera')),
                ('entera_sng', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SNG de la entera')),
                ('descremada_grasa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Grasa de la descremada')),
                ('descremada_sng', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SNG de la descremada')),
                ('litros_entera', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Litros de entera')),
                ('litros_descremada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Litros de descremada')),
                ('estado', models.CharField(choices=[('calculado', 'Calculado'), ('transferido', 'Transferido'), ('agitando', 'En agitación'), ('muestreado', 'Muestreado'), ('corrigiendo', 'En corrección'), ('liberado', 'Liberado'), ('anulado', 'Anulado')], db_index=True, default='calculado', max_length=20, verbose_name='Estado')),
                ('agitacion_desde', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de la agitación')),
                ('grasa_real', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grasa medida')),
                ('sng_real', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SNG medido')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(help_text='El producto al que se estandariza. De él sale el RC objetivo.', on_delete=django.db.models.deletion.PROTECT, related_name='vales_estandarizacion', to='maestros.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_estandarizacion', to=settings.AUTH_USER_MODEL)),
                ('silo_descremada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_como_descremada', to='maestros.silo')),
                ('silo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales_como_destino', to='maestros.silo')),
                ('silo_entera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales_como_entera', to='maestros.silo')),
            ],
            options={
                'verbose_name': 'Vale de estandarización',
                'verbose_name_plural': 'Vales de estandarización',
                'ordering': ['-fecha', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('volumen__gt', 0)), name='vale_volumen_positivo'), models.CheckConstraint(condition=models.Q(('rc_objetivo__gt', 0)), name='vale_rc_positivo')],
            },
        ),
    ]
