# Generated by Django 6.0.7 on 2026-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeestandarizacion',
            name='muestreado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se tomó la muestra. Congela «minutos agitando»: sin este sello el contador sigue creciendo contra el reloj actual y después no hay forma de saber si la muestra fue temprana.', null=True, verbose_name='Hora del muestreo'),
        ),
    ]
