# Generated by Django 6.0.7 on 2026-08-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0002_muestreado_en'),
        ('recepcion', '0018_analisis_silo'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeestandarizacion',
            name='analisis_descremada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_con_esta_descremada', to='recepcion.analisissilo', verbose_name='Análisis de la descremada'),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='analisis_entera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_con_esta_entera', to='recepcion.analisissilo', verbose_name='Análisis de la entera'),
        ),
    ]
