# Generated by Django 6.0.7 on 2026-08-25 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def conservar_codigo_existente(apps, schema_editor):
    Vale = apps.get_model("estandarizacion", "ValeEstandarizacion")
    for vale in Vale.objects.only("id", "codigo").iterator():
        Vale.objects.filter(pk=vale.pk).update(codigo_propuesto=vale.codigo)


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0003_procedencia_del_analisis'),
        ('maestros', '0031_sembrar_siglas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valeestandarizacion',
            name='abierto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='abierto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borradores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='codigo_propuesto',
            field=models.CharField(blank=True, max_length=40, verbose_name='Código definitivo propuesto'),
        ),
        migrations.RunPython(conservar_codigo_existente, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='descremada_grasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grasa de la descremada'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='descremada_sng',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SNG de la descremada'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='entera_grasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grasa de la entera'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='entera_sng',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SNG de la entera'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('calculado', 'Calculado'), ('transferido', 'Transferido'), ('agitando', 'En agitación'), ('muestreado', 'Muestreado'), ('corrigiendo', 'En corrección'), ('liberado', 'Liberado'), ('anulado', 'Anulado')], db_index=True, default='calculado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='litros_descremada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Litros de descremada'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='litros_entera',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Litros de entera'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='El producto al que se estandariza. De él sale el RC objetivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_estandarizacion', to='maestros.producto'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='rc_objetivo',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Materia grasa dividida por sólidos no grasos.', max_digits=6, null=True, verbose_name='RC objetivo'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='silo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_como_destino', to='maestros.silo'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='silo_entera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_como_entera', to='maestros.silo'),
        ),
        migrations.AlterField(
            model_name='valeestandarizacion',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En litros', max_digits=12, null=True, verbose_name='Volumen a preparar'),
        ),
    ]
