# Generated by Django 6.0.7 on 2026-08-25 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0004_valeestandarizacion_abierto_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionValeEstandarizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(max_length=30)),
                ('motivo', models.TextField()),
                ('cambios', models.JSONField(default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_vale_estandarizacion', to=settings.AUTH_USER_MODEL)),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='estandarizacion.valeestandarizacion')),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
            },
        ),
    ]
