# Generated by Django 6.0.7 on 2026-08-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0005_correccionvaleestandarizacion'),
        ('maestros', '0031_sembrar_siglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeestandarizacion',
            name='motivo_desvio_fifo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='silo_sugerido_fifo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_sugeridos_fifo', to='maestros.silo'),
        ),
    ]
