# Generated by Django 6.0.7 on 2026-08-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0006_valeestandarizacion_motivo_desvio_fifo_and_more'),
        ('maestros', '0031_sembrar_siglas'),
        ('recepcion', '0025_alter_movimientosilo_origen_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeestandarizacion',
            name='analisis_crema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_con_esta_crema', to='recepcion.analisissilo', verbose_name='Análisis de la crema'),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='crema_grasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grasa de la crema'),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='crema_sng',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SNG de la crema'),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='litros_crema',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Litros de crema'),
        ),
        migrations.AddField(
            model_name='valeestandarizacion',
            name='silo_crema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_como_crema', to='maestros.silo'),
        ),
    ]
