# Generated by Django 6.0.7 on 2026-09-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0007_valeestandarizacion_analisis_crema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeestandarizacion',
            name='codigo_propuesto',
        ),
    ]
