# Generated by Django 6.0.7 on 2026-09-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizacion', '0008_remove_valeestandarizacion_codigo_propuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeestandarizacion',
            name='ejecutado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se mezcló la leche: lo sella `transferir` con la misma hora de los movimientos de silo. Nadie lo teclea; nulo hasta transferir.', null=True, verbose_name='Ejecutado en'),
        ),
    ]
