# Generated by Django 6.0.7 on 2026-07-31 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0010_sembrar_equipos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('administracion', 'Administración general')], max_length=30)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('L', 'Litros'), ('un', 'Unidades')], max_length=5)),
                ('contenido_envase', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('demanda_anual', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('costo_por_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_mantencion_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('plazo_reposicion_dias', models.PositiveIntegerField(default=0)),
                ('consumo_diario', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['area', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloCIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('administracion', 'Administración general')], max_length=30)),
                ('equipo', models.CharField(max_length=120)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('observado', 'Observado')], default='programado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_kg', models.DecimalField(decimal_places=6, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_inventario', to='maestros.producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.insumo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('producto', 'insumo'), name='consumo_unico_producto_insumo')],
            },
        ),
    ]
