# Generated by Django 6.0.7 on 2026-08-03 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('produccion', '0003_alter_lote_kg_producidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('area', models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('administracion', 'Administración general')], default='bodega', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('materia_prima', 'Materia prima'), ('empaque', 'Material de empaque'), ('produccion', 'Insumo de producción'), ('quimico', 'Producto químico'), ('repuesto', 'Repuesto'), ('limpieza', 'Artículo de limpieza'), ('seguridad', 'Elemento de seguridad'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.AddField(
            model_name='insumo',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='requiere_calidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insumo',
            name='requiere_certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insumo',
            name='requiere_lote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='requiere_temperatura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insumo',
            name='requiere_vencimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_seguridad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='DetalleSolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, max_digits=16)),
                ('cantidad_aprobada', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('cantidad_entregada', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionMRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_corte', models.DateField()),
                ('horizonte_hasta', models.DateField()),
                ('parametros', models.JSONField(default=dict)),
                ('ejecutada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('entregada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('recibida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('elaboracion', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('estado_calidad', models.CharField(choices=[('no_requiere', 'No requiere inspección'), ('pendiente', 'Pendiente de inspección'), ('muestra', 'Muestra tomada'), ('analisis', 'En análisis'), ('aprobado', 'Aprobado'), ('observado', 'Aprobado con observaciones'), ('bloqueado', 'Bloqueado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('recibido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.insumo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.proveedor')),
            ],
            options={
                'ordering': ['vencimiento', 'recibido_en'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('muestra', 'Muestra tomada'), ('analisis', 'En análisis'), ('aprobada', 'Aprobada'), ('observada', 'Aprobada con observaciones'), ('rechazada', 'Rechazada'), ('bloqueada', 'Bloqueada')], default='pendiente', max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField(default=3)),
                ('resultados', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True)),
                ('decidida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_material', to=settings.AUTH_USER_MODEL)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inspeccion', to='inventario.loteinventario')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_fisica', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('cantidad_reservada', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.loteinventario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntregaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('detalle_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.detallesolicitudmaterial')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.entregaproduccion')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.loteinventario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=180)),
                ('mensaje', models.TextField()),
                ('documento_tipo', models.CharField(blank=True, max_length=80)),
                ('documento_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('enviada', 'Enviada'), ('parcial', 'Recibida parcialmente'), ('recibida', 'Recibida'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_comprometida', models.DateField(blank=True, null=True)),
                ('bodega_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=80)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('compra_minima', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('multiplo_compra', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('lead_time_dias', models.PositiveIntegerField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventario.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.CharField(max_length=80)),
                ('factura', models.CharField(blank=True, max_length=80)),
                ('recibida_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='inventario.ordencompra')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.detallesolicitudmaterial')),
                ('existencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.existencia')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoMRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_requerida', models.DateField()),
                ('necesidad_bruta', models.DecimalField(decimal_places=3, max_digits=16)),
                ('disponible_proyectado', models.DecimalField(decimal_places=3, max_digits=16)),
                ('recepciones_programadas', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('necesidad_neta', models.DecimalField(decimal_places=3, max_digits=16)),
                ('compra_sugerida', models.DecimalField(decimal_places=3, max_digits=16)),
                ('fecha_sugerida_orden', models.DateField()),
                ('explicacion', models.JSONField(default=dict)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='inventario.ejecucionmrp')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('area', models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('administracion', 'Administración general')], max_length=30)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida en orden de compra'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_compra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventario.solicitudcompra'),
        ),
        migrations.CreateModel(
            name='DetalleSolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('fecha_requerida', models.DateField()),
                ('origen_mrp', models.BooleanField(default=False)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.solicitudcompra')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('area', models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('administracion', 'Administración general')], max_length=30)),
                ('fecha_requerida', models.DateField()),
                ('prioridad', models.PositiveSmallIntegerField(default=3)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('preparando', 'En preparación'), ('preparada', 'Preparada'), ('parcial', 'Entrega parcial'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('lote_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_material', to='produccion.lote')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrq_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entregaproduccion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='inventario.solicitudmaterial'),
        ),
        migrations.AddField(
            model_name='detallesolicitudmaterial',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.solicitudmaterial'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('disponible', 'Disponible'), ('cuarentena', 'Cuarentena'), ('rechazado', 'Rechazado'), ('produccion', 'Producción')], default='disponible', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='inventario.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepción'), ('liberacion', 'Liberación de Calidad'), ('bloqueo', 'Bloqueo'), ('rechazo', 'Rechazo'), ('traslado', 'Traslado'), ('reserva', 'Reserva'), ('liberar_reserva', 'Liberación de reserva'), ('entrega', 'Entrega a Producción'), ('devolucion', 'Devolución desde Producción'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('merma', 'Merma')], max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('documento_tipo', models.CharField(max_length=80)),
                ('documento_id', models.PositiveBigIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=3, max_digits=16)),
                ('saldo_posterior', models.DecimalField(decimal_places=3, max_digits=16)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.loteinventario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.ubicacion')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='existencia',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.ubicacion'),
        ),
        migrations.CreateModel(
            name='DetalleRecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, max_digits=16)),
                ('cantidad_danada', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('embalaje_conforme', models.BooleanField(default=True)),
                ('certificado_recibido', models.BooleanField(default=False)),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='inventario.detalleordencompra')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_recepcion', to='inventario.loteinventario')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.recepcioncompra')),
                ('ubicacion_temporal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loteinventario',
            constraint=models.UniqueConstraint(fields=('insumo', 'codigo', 'proveedor'), name='lote_inventario_unico'),
        ),
        migrations.AddConstraint(
            model_name='insumoproveedor',
            constraint=models.UniqueConstraint(fields=('insumo', 'proveedor'), name='insumo_proveedor_unico'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('bodega', 'codigo'), name='ubicacion_unica_bodega'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.UniqueConstraint(fields=('lote', 'ubicacion'), name='existencia_unica_lote_ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_fisica__gte', 0)), name='existencia_fisica_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_reservada__gte', 0)), name='existencia_reservada_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_reservada__lte', models.F('cantidad_fisica'))), name='reserva_no_supera_fisico'),
        ),
    ]
