# Generated by Django 6.0.7 on 2026-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_bodega_proveedor_insumo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('administracion', 'Administración general')], default='bodega', max_length=30),
        ),
        migrations.AlterField(
            model_name='ciclocip',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('administracion', 'Administración general')], max_length=30),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('administracion', 'Administración general')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('administracion', 'Administración general')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('administracion', 'Administración general')], max_length=30),
        ),
    ]
