# Generated by Django 6.0.7 on 2026-08-03 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_bodega_area_alter_ciclocip_area_and_more'),
        ('usuarios', '0005_empresa_perfilusuario_empresa_sucursal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='usuarios.sucursal'),
        ),
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(max_length=80)),
                ('documento_id', models.PositiveBigIntegerField()),
                ('etapa', models.CharField(default='jefatura', max_length=80)),
                ('decision', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'id'],
                'constraints': [models.UniqueConstraint(fields=('documento_tipo', 'documento_id', 'etapa'), name='aprobacion_unica_por_etapa')],
            },
        ),
    ]
