# Generated by Django 6.0.7 on 2026-08-03 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_bodega_sucursal_aprobacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(max_length=80)),
                ('documento_id', models.PositiveBigIntegerField()),
                ('tipo', models.CharField(max_length=40)),
                ('archivo', models.FileField(upload_to='abastecimiento/%Y/%m/')),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('severidad', models.CharField(choices=[('info', 'Informativa'), ('advertencia', 'Advertencia'), ('critica', 'Crítica')], max_length=15)),
                ('mensaje', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.loteinventario')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='LiberacionExcepcionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('uso_especifico', models.TextField()),
                ('justificacion', models.TextField()),
                ('autorizada_en', models.DateTimeField(auto_now_add=True)),
                ('vence_en', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('aprobada_calidad_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excepciones_calidad', to=settings.AUTH_USER_MODEL)),
                ('aprobada_jefatura_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excepciones_jefatura', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones_excepcionales', to='inventario.loteinventario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excepciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoConformidadMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('destino', models.CharField(choices=[('devolucion', 'Devolución al proveedor'), ('destruccion', 'Destrucción'), ('reinspeccion', 'Reinspección'), ('reproceso', 'Reproceso'), ('excepcional', 'Liberación excepcional')], max_length=20)),
                ('cerrada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='inventario.inspeccionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('categoria', models.CharField(blank=True, choices=[('materia_prima', 'Materia prima'), ('empaque', 'Material de empaque'), ('produccion', 'Insumo de producción'), ('quimico', 'Producto químico'), ('repuesto', 'Repuesto'), ('limpieza', 'Artículo de limpieza'), ('seguridad', 'Elemento de seguridad'), ('otro', 'Otro')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('campos', models.JSONField(default=list, help_text='Campos configurables y sus límites')),
                ('activa', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_inspeccion', to='inventario.insumo')),
            ],
        ),
        migrations.AddField(
            model_name='inspeccionmaterial',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.plantillainspeccion'),
        ),
        migrations.AddConstraint(
            model_name='plantillainspeccion',
            constraint=models.UniqueConstraint(fields=('nombre', 'version'), name='plantilla_inspeccion_version_unica'),
        ),
    ]
