# Generated by Django 6.0.7 on 2026-08-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_adjunto_alerta_liberacionexcepcionalmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='vida_util_dias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
