# Generated by Django 6.0.7 on 2026-08-03 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_insumo_vida_util_dias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('positivo', 'Ajuste positivo'), ('negativo', 'Ajuste negativo'), ('merma', 'Merma')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('aplicado', 'Aplicado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('existencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.existencia')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('estado_material', models.CharField(choices=[('utilizable', 'Utilizable'), ('danado', 'Dañado'), ('merma', 'Merma')], max_length=15)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventario.detalleentregaproduccion')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
