# Generated by Django 6.0.7 on 2026-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_ajusteinventario_devolucionproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('liberacion', 'Liberación de Calidad'), ('bloqueo', 'Bloqueo'), ('rechazo', 'Rechazo'), ('traslado', 'Traslado'), ('reserva', 'Reserva'), ('liberar_reserva', 'Liberación de reserva'), ('entrega', 'Entrega a Producción'), ('salida', 'Salida de Bodega'), ('consumo', 'Consumo de material'), ('devolucion', 'Devolución desde Producción'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('merma', 'Merma')], max_length=25),
        ),
    ]
