# Generated by Django 6.0.7 on 2026-08-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_movimientoinventario_tipo'),
        ('produccion', '0003_alter_lote_kg_producidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoLoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_produccion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consumo_inventario', to='produccion.lote')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
