# Generated by Django 6.0.7 on 2026-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_consumoloteproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración general')], default='bodega', max_length=30),
        ),
        migrations.AlterField(
            model_name='ciclocip',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración general')], max_length=30),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración general')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración general')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='area',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración general')], max_length=30),
        ),
    ]
