# Generated by Django 6.0.7 on 2026-08-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_ciclocip_equipo_al_maestro'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumoproducto',
            name='consumo_unico_producto_insumo',
        ),
        migrations.DeleteModel(
            name='ConsumoProducto',
        ),
    ]
