# Generated by Django 6.0.7 on 2026-08-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_consumoproducto_consumo_unico_producto_insumo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='stock_actual',
        ),
    ]
