# Generated by Django 6.0.7 on 2026-08-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_insumo_stock_actual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecucionmrp',
            options={'ordering': ['-creada_en', '-id']},
        ),
    ]
