# Generated by Django 6.0.7 on 2026-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_ejecucion_mrp_mas_reciente_primero'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='insumoproveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('insumo',), name='insumo_un_solo_proveedor_principal'),
        ),
    ]
