# Generated by Django 6.0.7 on 2026-08-04 20:26

"""
Une las dos ramas de migraciones de `inventario`.

Main y esta rama partieron las dos desde `0009_consumoloteproduccion`: main
agregó las áreas nuevas —despacho, mantenimiento— a los campos `area`, y aquí
se hizo la referencia de CicloCIP al maestro de equipos, se eliminó
ConsumoProducto y se agregaron las restricciones de inventario.

No se renumeró ninguna de las dos a propósito. Renumerar rompe el registro de
quien ya las aplicó: Django compara por nombre, así que la migración renombrada
se intentaría aplicar de nuevo. Una fusión deja las dos historias intactas.

Las ramas no se pisan —tocan campos distintos— así que la fusión no lleva
operaciones.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_bodega_area_alter_ciclocip_area_and_more'),
        ('inventario', '0014_un_solo_proveedor_principal'),
    ]

    operations = [
    ]
