# Generated by Django 6.0.7 on 2026-08-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_merge_ramas_de_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liberacionexcepcionalmaterial',
            options={'ordering': ['-autorizada_en']},
        ),
        migrations.AlterModelOptions(
            name='noconformidadmaterial',
            options={'ordering': ['cerrada', '-creada_en']},
        ),
        migrations.AddField(
            model_name='noconformidadmaterial',
            name='accion_tomada',
            field=models.TextField(blank=True, help_text='Qué se hizo con el material. Obligatoria para cerrar.', verbose_name='Acción tomada'),
        ),
        migrations.AddField(
            model_name='noconformidadmaterial',
            name='cerrada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noconformidadmaterial',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noconformidadmaterial',
            name='liberacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='inventario.liberacionexcepcionalmaterial', verbose_name='Liberación excepcional que la resolvió'),
        ),
        migrations.AddConstraint(
            model_name='noconformidadmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('cerrada', False), models.Q(('cerrada_por__isnull', False), ('cerrada_en__isnull', False), models.Q(('accion_tomada', ''), _negated=True)), _connector='OR'), name='nc_cerrada_dice_quien_cuando_y_que_hizo'),
        ),
    ]
