# Generated by Django 6.0.7 on 2026-08-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_no_conformidad_con_cierre_trazable'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='liberacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.liberacionexcepcionalmaterial', verbose_name='Concesión que la autorizó'),
        ),
    ]
