# Generated by Django 6.0.7 on 2026-08-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_tenant_inventario_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionmrp',
            name='error',
            field=models.TextField(blank=True, verbose_name='Motivo del fallo'),
        ),
        migrations.AddField(
            model_name='ejecucionmrp',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'En cola'), ('en_curso', 'Calculando'), ('terminada', 'Terminada'), ('fallida', 'Fallida')], db_index=True, default='terminada', max_length=12, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ejecucionmrp',
            name='terminada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
