# Generated by Django 6.0.7 on 2026-08-17 21:09

import django.db.models.deletion
import usuarios.tenancy
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_aseos_cip'),
        ('produccion', '0009_registroenvase_palletproducto_and_more'),
        ('usuarios', '0014_alter_perfilusuario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=180)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(default=usuarios.tenancy.empresa_predeterminada_pruebas, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_despacho', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('autorizado', 'Autorizado'), ('despachado', 'Despachado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=15)),
                ('guia_despacho', models.CharField(blank=True, max_length=60)),
                ('transportista', models.CharField(blank=True, max_length=150)),
                ('patente', models.CharField(blank=True, max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('despachado_en', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='inventario.clientedespacho')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_creados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(default=usuarios.tenancy.sucursal_predeterminada_pruebas, on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='usuarios.sucursal')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.despacho')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_despacho', to='produccion.palletproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ExistenciaProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pallet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='existencia_producto', to='produccion.palletproducto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_terminados', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['pallet__codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.UUIDField(db_index=True, unique=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('transferencia', 'Transferencia'), ('despacho', 'Despacho')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.despacho')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to='inventario.ubicacion')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_producto', to='inventario.ubicacion')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='produccion.palletproducto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientedespacho',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='cliente_despacho_codigo_empresa'),
        ),
        migrations.AddConstraint(
            model_name='despacho',
            constraint=models.UniqueConstraint(fields=('sucursal', 'numero'), name='despacho_numero_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='detalledespacho',
            constraint=models.UniqueConstraint(fields=('despacho', 'pallet'), name='despacho_pallet_unico'),
        ),
    ]
