# Generated by Django 6.0.7 on 2026-08-17 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_clientedespacho_despacho_detalledespacho_and_more'),
        ('produccion', '0009_registroenvase_palletproducto_and_more'),
        ('usuarios', '0014_alter_perfilusuario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['sucursal', 'estado', '-creado_en'], name='desp_suc_est_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoproductoterminado',
            index=models.Index(fields=['pallet', '-registrado_en'], name='mov_pt_pallet_fecha_idx'),
        ),
    ]
