# Generated by Django 6.0.7 on 2026-08-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_despacho_desp_suc_est_fecha_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajusteinventario',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='existencia',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inspeccionmaterial',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='solicitudmaterial',
            options={'ordering': ['-id']},
        ),
    ]
