# Generated by Django 6.0.7 on 2026-08-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_ajusteinventario_options_and_more'),
        ('procesos', '0010_entradaproceso_motivo_salidaproceso_clasificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDespachoGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidad', models.CharField(max_length=20)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_granel', to='inventario.despacho')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_despacho_granel', to='procesos.salidaproceso')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('despacho', 'salida'), name='despacho_salida_granel_unica'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='despacho_granel_cantidad_positiva')],
            },
        ),
    ]
