# Generated by Django 6.0.7 on 2026-09-03 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


def asignar_operaciones_unicas(apps, schema_editor):
    Detalle = apps.get_model('inventario', 'DetalleDespachoGranel')
    for detalle in Detalle.objects.filter(operacion_id__isnull=True).iterator():
        detalle.operacion_id = uuid.uuid4()
        detalle.save(update_fields=['operacion_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_detalledespachogranel'),
        ('recepcion', '0027_despacholeche_anulado_en_despacholeche_anulado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledespachogranel',
            name='movimiento_silo',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_despacho_granel', to='recepcion.movimientosilo'),
        ),
        migrations.AddField(
            model_name='detalledespachogranel',
            name='operacion_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(asignar_operaciones_unicas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='detalledespachogranel',
            name='operacion_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
