# Generated by Django 6.0.7 on 2026-09-03 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def conservar_consumos_historicos(apps, schema_editor):
    Consumo = apps.get_model("inventario", "ConsumoLoteProduccion")
    Consumo.objects.update(fase="completo_legacy")


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_detalledespachogranel_movimiento_silo_and_more'),
        ('produccion', '0014_pallet_kg_maximo_500'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoloteproduccion',
            name='fase',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('envasado', 'Envasado'), ('completo_legacy', 'Receta completa (histórico)')], default='proceso', max_length=20),
        ),
        migrations.AddField(
            model_name='consumoloteproduccion',
            name='operacion_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consumoloteproduccion',
            name='lote_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_inventario', to='produccion.lote'),
        ),
        migrations.RunPython(
            conservar_consumos_historicos,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='consumoloteproduccion',
            constraint=models.UniqueConstraint(condition=models.Q(('fase__in', ['proceso', 'completo_legacy'])), fields=('lote_produccion', 'fase'), name='consumo_unico_lote_fase_cierre'),
        ),
    ]
