# Generated by Django 6.0.7 on 2026-09-04 14:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def materializar_rework_historico(apps, schema_editor):
    Autorizacion = apps.get_model("procesos", "AutorizacionReproceso")
    Entrada = apps.get_model("procesos", "EntradaProceso")
    Bodega = apps.get_model("inventario", "Bodega")
    Ubicacion = apps.get_model("inventario", "Ubicacion")
    Unidad = apps.get_model("inventario", "UnidadRework")
    Movimiento = apps.get_model("inventario", "MovimientoRework")

    for autorizacion in Autorizacion.objects.select_related("lote__sucursal").iterator():
        usuario_id = autorizacion.decidido_por_id or autorizacion.solicitado_por_id
        # Las decisiones antiguas sin autor siguen siendo legibles por la vía
        # legada; no se inventa una firma de auditoría durante el backfill.
        if not usuario_id:
            continue
        sucursal = autorizacion.lote.sucursal
        bodega, _ = Bodega.objects.get_or_create(
            sucursal=sucursal, codigo="BRW",
            defaults={"nombre": "Bodega segregada de rework", "area": "bodega"},
        )
        tipo_ubicacion = "disponible" if autorizacion.estado == "aprobado" else (
            "rechazado" if autorizacion.estado == "destruido" else "cuarentena"
        )
        codigo = {
            "disponible": "RW-DISP", "rechazado": "RW-RECH",
            "cuarentena": "RW-CUAR",
        }[tipo_ubicacion]
        ubicacion, _ = Ubicacion.objects.get_or_create(
            bodega=bodega, codigo=codigo,
            defaults={"tipo": tipo_ubicacion, "descripcion": "Rework histórico migrado"},
        )
        consumido = Entrada.objects.filter(
            lote_id=autorizacion.lote_id, tipo="reproceso"
        ).aggregate(total=models.Sum("cantidad"))["total"] or Decimal("0")
        saldo = max(autorizacion.cantidad_kg - consumido, Decimal("0"))
        estado = {
            "aprobado": "disponible" if saldo > 0 else "consumido",
            "destruido": "destruido",
        }.get(autorizacion.estado, "bloqueado")
        if estado == "destruido":
            saldo = Decimal("0")
        unidad = Unidad.objects.create(
            autorizacion=autorizacion, codigo=f"RW-{autorizacion.pk:06d}",
            ubicacion=ubicacion, estado=estado,
            cantidad_inicial_kg=autorizacion.cantidad_kg,
            cantidad_disponible_kg=saldo,
        )
        Movimiento.objects.create(
            unidad=unidad, tipo="segregacion", cantidad_kg=autorizacion.cantidad_kg,
            destino=ubicacion, motivo="Existencia histórica materializada",
            registrado_por_id=usuario_id, saldo_anterior_kg=0,
            saldo_posterior_kg=autorizacion.cantidad_kg,
        )
        if consumido > 0:
            Movimiento.objects.create(
                unidad=unidad, tipo="consumo",
                cantidad_kg=min(consumido, autorizacion.cantidad_kg),
                origen=ubicacion, motivo="Consumo histórico conciliado",
                registrado_por_id=usuario_id,
                saldo_anterior_kg=autorizacion.cantidad_kg,
                saldo_posterior_kg=saldo,
            )
        if estado == "destruido":
            Movimiento.objects.create(
                unidad=unidad, tipo="destruccion", cantidad_kg=autorizacion.cantidad_kg,
                origen=ubicacion, motivo="Destrucción histórica conciliada",
                registrado_por_id=usuario_id,
                saldo_anterior_kg=autorizacion.cantidad_kg, saldo_posterior_kg=0,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_consumoloteproduccion_fase_and_more'),
        ('procesos', '0020_reparar_lotes_suero_mantequilla'),
        ('produccion', '0015_registroenvase_formato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('estado', models.CharField(choices=[('pendiente_ubicacion', 'Aprobado; pendiente de Bodega'), ('disponible', 'Disponible para producción'), ('bloqueado', 'Bloqueado'), ('consumido', 'Consumido'), ('destruido', 'Destruido')], db_index=True, default='bloqueado', max_length=24)),
                ('cantidad_inicial_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cantidad_disponible_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_fisicas', to='procesos.autorizacionreproceso')),
                ('pallet_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_rework', to='produccion.palletproducto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_rework', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('segregacion', 'Segregación'), ('habilitacion', 'Habilitación por Bodega'), ('traslado', 'Traslado'), ('bloqueo', 'Bloqueo'), ('consumo', 'Consumo en producción'), ('destruccion', 'Destrucción'), ('ajuste', 'Ajuste identificado')], max_length=20)),
                ('cantidad_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('motivo', models.CharField(max_length=250)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('saldo_anterior_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_posterior_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_entradas', to='inventario.ubicacion')),
                ('entrada_proceso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_rework', to='procesos.entradaproceso')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_salidas', to='inventario.ubicacion')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_rework', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.unidadrework')),
            ],
            options={
                'ordering': ['-registrado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='unidadrework',
            index=models.Index(fields=['estado', 'ubicacion'], name='rw_estado_ubic_idx'),
        ),
        migrations.AddConstraint(
            model_name='unidadrework',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_inicial_kg__gt', 0)), name='rework_cantidad_inicial_positiva'),
        ),
        migrations.AddConstraint(
            model_name='unidadrework',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible_kg__gte', 0)), name='rework_disponible_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='unidadrework',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible_kg__lte', models.F('cantidad_inicial_kg'))), name='rework_disponible_no_supera_inicial'),
        ),
        migrations.AddIndex(
            model_name='movimientorework',
            index=models.Index(fields=['unidad', '-registrado_en'], name='rw_mov_unidad_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientorework',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_kg__gt', 0)), name='movimiento_rework_cantidad_positiva'),
        ),
        migrations.RunPython(materializar_rework_historico, migrations.RunPython.noop),
    ]
