# Generated by Django 6.0.7 on 2026-07-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0002_vehiculo_silo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Litros')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('origen_tipo', models.CharField(blank=True, choices=[('recepcion', 'Recepción'), ('lote', 'Consumo de lote'), ('ajuste', 'Ajuste manual')], max_length=20, verbose_name='Origen')),
                ('origen_id', models.PositiveIntegerField(blank=True, help_text='Id de la recepción o del lote que provocó el movimiento', null=True, verbose_name='Registro de origen')),
                ('motivo', models.TextField(blank=True, help_text='Obligatorio en los ajustes', verbose_name='Motivo')),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='maestros.silo', verbose_name='Silo')),
            ],
            options={
                'verbose_name': 'Movimiento de silo',
                'verbose_name_plural': 'Movimientos de silo',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['silo', 'fecha_hora'], name='recepcion_m_silo_id_06b8d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('guia', models.CharField(blank=True, max_length=60, verbose_name='Guía')),
                ('procedencia', models.CharField(blank=True, choices=[('Nestlé', 'Nestlé'), ('P. Unión', 'P. Unión')], max_length=20, verbose_name='Procedencia')),
                ('tipo_leche', models.CharField(choices=[('Entera', 'Entera'), ('Descremada', 'Descremada')], max_length=20, verbose_name='Tipo de leche')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Litros')),
                ('turno', models.CharField(blank=True, choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], max_length=5, verbose_name='Turno')),
                ('controles', models.JSONField(blank=True, default=dict, help_text='{"delvo": "Negativo", "acidez": 16.5, "ph": 6.7, ...}', verbose_name='Controles del camión')),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('muestreada', 'Muestreada'), ('analizada', 'Analizada'), ('liberada', 'Liberada'), ('retenida', 'Retenida'), ('descargada', 'Descargada'), ('cerrada', 'Cerrada')], default='registrada', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, help_text='Obligatorio si la recepción se retiene', verbose_name='Motivo')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('silo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='maestros.silo', verbose_name='Silo de destino')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='maestros.vehiculo', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Recepción de leche',
                'verbose_name_plural': 'Recepciones de leche',
                'ordering': ['-fecha', '-hora'],
                'constraints': [models.CheckConstraint(condition=models.Q(('litros__gte', 0)), name='recepcion_litros_no_negativos')],
            },
        ),
    ]
