# Generated by Django 6.0.7 on 2026-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_sembrar_equipos'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientosilo',
            constraint=models.UniqueConstraint(condition=models.Q(('origen_tipo', 'recepcion')), fields=('origen_tipo', 'origen_id'), name='una_descarga_por_recepcion'),
        ),
    ]
