# Generated by Django 6.0.7 on 2026-08-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0016_frecuencia_de_los_checklists'),
        ('recepcion', '0002_movimientosilo_una_descarga_por_recepcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='calidad_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de decisión'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='calidad_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_calidad_recepcion', to=settings.AUTH_USER_MODEL, verbose_name='Decisión de calidad por'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='codigo_muestra',
            field=models.CharField(blank=True, max_length=80, verbose_name='Código de muestra'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='modulo',
            field=models.CharField(blank=True, help_text='Identificador del módulo transportado dentro del camión', max_length=40, verbose_name='Módulo / compartimiento'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='muestreado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de muestreo'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='muestreado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_recepcion_tomadas', to=settings.AUTH_USER_MODEL, verbose_name='Muestreado por'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='silo_asignado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de asignación'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='silo_asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silos_recepcion_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Silo asignado por'),
        ),
        migrations.AddConstraint(
            model_name='recepcion',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_muestra', ''), _negated=True), fields=('codigo_muestra',), name='codigo_muestra_recepcion_unico'),
        ),
    ]
