# Generated by Django 6.0.7 on 2026-08-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_recepcion_calidad_en_recepcion_calidad_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='estado',
            field=models.CharField(choices=[('registrada', 'En espera de muestra'), ('muestreada', 'Muestra tomada'), ('analizada', 'Analizada'), ('liberada', 'Aprobada por Calidad'), ('retenida', 'Retenida'), ('descargada', 'Descargada'), ('cerrada', 'Cerrada')], default='registrada', max_length=20, verbose_name='Estado'),
        ),
    ]
