# Generated by Django 6.0.7 on 2026-08-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_alter_recepcion_estado'),
        ('recoleccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='carga_recoleccion',
            field=models.OneToOneField(blank=True, help_text='Vínculo opcional para conservar recepciones manuales autorizadas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_planta', to='recoleccion.cargamodulo', verbose_name='Carga esperada de Recolección'),
        ),
    ]
