# Generated by Django 6.0.7 on 2026-08-17 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0028_remove_silo_silo_capacidad_no_negativa_silo_estado_and_more'),
        ('produccion', '0008_ordenproduccion_lote_orden_and_more'),
        ('recepcion', '0009_llegada_id_por_recepcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosilo',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_silo', to='maestros.equipo'),
        ),
        migrations.AddField(
            model_name='movimientosilo',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_silo', to='produccion.lote'),
        ),
        migrations.AddField(
            model_name='movimientosilo',
            name='operacion_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Clave idempotente compartida por los asientos de una operación.', null=True),
        ),
        migrations.AddField(
            model_name='movimientosilo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_silo', to='maestros.producto'),
        ),
        migrations.AddField(
            model_name='movimientosilo',
            name='silo_contraparte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_contraparte', to='maestros.silo'),
        ),
        migrations.AddField(
            model_name='movimientosilo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_silo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientosilo',
            name='origen_tipo',
            field=models.CharField(blank=True, choices=[('recepcion', 'Recepción'), ('estandarizacion', 'Estandarización'), ('lote', 'Consumo de lote'), ('transferencia', 'Transferencia'), ('produccion', 'Producción'), ('merma', 'Merma'), ('devolucion', 'Devolución'), ('rework', 'Reproceso'), ('ajuste', 'Ajuste manual')], max_length=20, verbose_name='Origen'),
        ),
        migrations.AddConstraint(
            model_name='movimientosilo',
            constraint=models.UniqueConstraint(condition=models.Q(('operacion_id__isnull', False)), fields=('operacion_id', 'silo', 'tipo'), name='asiento_silo_unico_por_operacion'),
        ),
    ]
