# Generated by Django 6.0.7 on 2026-08-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0010_movimientosilo_equipo_movimientosilo_lote_and_more'),
        ('recoleccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='1 a 4, como las columnas M1-M4 del formato', verbose_name='Módulo')),
                ('crioscopia', models.DecimalField(blank=True, decimal_places=3, help_text='Un valor MENOS negativo que el límite sugiere agua añadida', max_digits=6, null=True, verbose_name='Crioscopía')),
                ('carga_recoleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modulos_recepcion', to='recoleccion.cargamodulo', verbose_name='Carga esperada de Recolección')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='recepcion.recepcion', verbose_name='Recepción')),
            ],
            options={
                'verbose_name': 'Módulo de la recepción',
                'verbose_name_plural': 'Módulos de la recepción',
                'ordering': ['recepcion', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('recepcion', 'numero'), name='modulo_unico_por_recepcion'), models.CheckConstraint(condition=models.Q(('numero__gte', 1)), name='modulo_numero_positivo')],
            },
        ),
    ]
