# Generated by Django 6.0.7 on 2026-08-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0012_modulos_desde_recepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion',
            name='carga_recoleccion',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='llegada_id',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='modulo',
        ),
    ]
