# Generated by Django 6.0.7 on 2026-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0013_recepcion_sin_modulo'),
        ('recoleccion', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modulorecepcion',
            constraint=models.UniqueConstraint(condition=models.Q(('carga_recoleccion__isnull', False)), fields=('carga_recoleccion',), name='una_recepcion_por_carga_recoleccion'),
        ),
    ]
