# Generated by Django 6.0.7 on 2026-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0014_carga_recoleccion_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='certificada',
            field=models.BooleanField(blank=True, help_text='Nulo = no se registró, que no es lo mismo que no certificada', null=True, verbose_name='Leche certificada'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_arribo_porteria',
            field=models.TimeField(blank=True, null=True, verbose_name='Arribo a portería'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_inicio_cip',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio del lavado CIP'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_inicio_descarga',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio de descarga'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_programa',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora programa'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_termino_cip',
            field=models.TimeField(blank=True, null=True, verbose_name='Término del lavado CIP'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='hora_termino_descarga',
            field=models.TimeField(blank=True, null=True, verbose_name='Término de descarga'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='kg_romana',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='El pesaje real. Los kilos de guía se derivan de los litros.', max_digits=12, null=True, verbose_name='Kilos (romana)'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='lavado_ruedas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Lavado de ruedas'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='ph_camion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Del enjuague del camión (5,5 a 8,5), NO de la leche. Mezclarlo con el pH de la leche haría que el agua retuviera un camión conforme.', max_digits=4, null=True, verbose_name='pH del camión'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='recambio_dilucion',
            field=models.CharField(blank=True, choices=[('recambio', 'Recambio'), ('ok', 'OK')], max_length=20, verbose_name='Cambio de dilución'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='relavado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vuelve a lavarse e ingresa'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='uso',
            field=models.CharField(blank=True, choices=[('despacho', 'Despacho'), ('stock', 'Stock'), ('semi', 'Precondensado semidescremado'), ('entero', 'Precondensado entero'), ('le', 'Leche entera'), ('suero', 'Suero'), ('antibiotico', 'Antibiótico')], max_length=20, verbose_name='Uso'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='uso_numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N° de destino'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('CCAA', 'CCAA'), ('Nestlé', 'Nestlé'), ('Colun', 'Colun'), ('P. Unión', 'P. Unión')], max_length=20, verbose_name='Procedencia'),
        ),
    ]
