# Generated by Django 6.0.7 on 2026-08-19 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0015_recepcion_instructivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlInhibidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tri_sensor', 'Tri Sensor'), ('charm', 'Charm'), ('delvo_sp', 'Delvo SP')], default='tri_sensor', max_length=20, verbose_name='Método')),
                ('tiras_usadas', models.PositiveSmallIntegerField(default=0, help_text='El formato las totaliza al pie: es control de consumo', verbose_name='Tiras usadas')),
                ('hora_lectura', models.TimeField(blank=True, null=True, verbose_name='Hora de lectura')),
                ('resultado', models.CharField(choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=20, verbose_name='Resultado')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_inhibidores', to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_inhibidores', to='recepcion.recepcion', verbose_name='Recepción')),
            ],
            options={
                'verbose_name': 'Control de inhibidores (PPRO N°1)',
                'verbose_name_plural': 'Controles de inhibidores (PPRO N°1)',
                'ordering': ['recepcion', 'hora_lectura'],
            },
        ),
        migrations.CreateModel(
            name='BusquedaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=160, verbose_name='Proveedor')),
                ('charm_bet', models.CharField(blank=True, choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=20, verbose_name='Charm rosa Bet')),
                ('charm_tetra', models.CharField(blank=True, choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=20, verbose_name='Charm rosa Tetra')),
                ('delvo_sp', models.CharField(blank=True, choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=20, verbose_name='Delvo SP')),
                ('hora_lectura', models.TimeField(blank=True, null=True, verbose_name='Hora de lectura')),
                ('resultado', models.CharField(choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=20, verbose_name='Resultado')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to='recepcion.controlinhibidores', verbose_name='Control de inhibidores')),
            ],
            options={
                'verbose_name': 'Búsqueda a proveedor',
                'verbose_name_plural': 'Búsquedas a proveedores',
                'ordering': ['control', 'proveedor'],
            },
        ),
    ]
