# Generated by Django 6.0.7 on 2026-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0016_inhibidores'),
        ('recoleccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modulorecepcion',
            name='modulo_numero_positivo',
        ),
        migrations.AddConstraint(
            model_name='modulorecepcion',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('numero__lte', 4)), name='modulo_numero_en_rango'),
        ),
    ]
