# Generated by Django 6.0.7 on 2026-08-19 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0028_remove_silo_silo_capacidad_no_negativa_silo_estado_and_more'),
        ('recepcion', '0017_modulo_numero_en_rango'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomado_en', models.DateTimeField(help_text='Fecha y hora en que se muestreó el silo. Fija la vigencia del análisis.', verbose_name='Hora de toma de muestra')),
                ('hora_inicio_llenado', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio de llenado')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH')),
                ('acidez', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Acidez (°Th)')),
                ('grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grasa (%)')),
                ('sng', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SNG (%)')),
                ('proteina', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Proteína (%)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('densidad', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Densidad (kg/m³)')),
                ('certificada', models.BooleanField(blank=True, help_text='Nulo = no se registró, que no es lo mismo que no certificada', null=True, verbose_name='Leche certificada')),
                ('procedencia', models.CharField(blank=True, choices=[('CCAA', 'CCAA'), ('Nestlé', 'Nestlé'), ('Colun', 'Colun'), ('P. Unión', 'P. Unión')], max_length=20, verbose_name='Procedencia')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_silo', to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis', to='maestros.silo', verbose_name='Silo')),
            ],
            options={
                'verbose_name': 'Análisis de silo',
                'verbose_name_plural': 'Análisis de silo',
                'ordering': ['-tomado_en'],
                'indexes': [models.Index(fields=['silo', '-tomado_en'], name='recepcion_a_silo_id_9be47c_idx')],
                'constraints': [models.UniqueConstraint(fields=('silo', 'tomado_en'), name='analisis_silo_unico_por_momento')],
            },
        ),
    ]
