# Generated by Django 6.0.7 on 2026-08-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0018_analisis_silo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='abierto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='abierto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borradores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('registrada', 'En espera de muestra'), ('muestreada', 'Muestra tomada'), ('analizada', 'Analizada'), ('liberada', 'Aprobada por Calidad'), ('retenida', 'Retenida'), ('descargada', 'Descargada'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
