# Generated by Django 6.0.7 on 2026-08-25 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def confirmar_analisis_existentes(apps, schema_editor):
    AnalisisSilo = apps.get_model("recepcion", "AnalisisSilo")
    AnalisisSilo.objects.update(estado="confirmado")


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0019_recepcion_abierto_en_recepcion_abierto_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisissilo',
            name='abierto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='abierto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borradores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='borrador', max_length=15),
        ),
        migrations.RunPython(
            confirmar_analisis_existentes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
