# Generated by Django 6.0.7 on 2026-08-25 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0031_sembrar_siglas'),
        ('recepcion', '0020_analisissilo_abierto_en_analisissilo_abierto_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCalidadSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_calidad_silo', to='recepcion.recepcion')),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_calidad_recepcion', to='maestros.silo')),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorreccionRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(max_length=30)),
                ('motivo', models.TextField()),
                ('cambios', models.JSONField(default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='recepcion.recepcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_recepcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
            },
        ),
    ]
