# Generated by Django 6.0.7 on 2026-08-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0021_alertacalidadsilo_correccionrecepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtribucionRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.PositiveSmallIntegerField()),
                ('origen_no_atribuible', models.CharField(blank=True, max_length=160)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuciones_recepcion', to='recepcion.movimientosilo')),
                ('recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuciones_silo', to='recepcion.recepcion')),
            ],
            options={
                'ordering': ['movimiento_id', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('movimiento', 'orden'), name='atribucion_orden_unico_por_movimiento'), models.CheckConstraint(condition=models.Q(('litros__gt', 0)), name='atribucion_litros_positivos'), models.CheckConstraint(condition=models.Q(models.Q(('origen_no_atribuible', ''), ('recepcion__isnull', False)), models.Q(('recepcion__isnull', True), models.Q(('origen_no_atribuible', ''), _negated=True)), _connector='OR'), name='atribucion_recepcion_o_motivo')],
            },
        ),
    ]
