# Generated by Django 6.0.7 on 2026-08-25 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0022_atribucionrecepcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisissilo',
            name='alcohol_75_conforme',
            field=models.BooleanField(blank=True, null=True, verbose_name='Prueba de alcohol 75° conforme'),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='hervor_conforme',
            field=models.BooleanField(blank=True, null=True, verbose_name='Prueba de hervor conforme'),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='hora_lectura',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de lectura'),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='inhibidores_resultado',
            field=models.CharField(blank=True, choices=[('negativo', 'Negativo'), ('positivo', 'Positivo')], max_length=20, verbose_name='Resultado de inhibidores'),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='metodo',
            field=models.CharField(blank=True, choices=[('tri_sensor', 'Tri Sensor'), ('charm', 'Charm'), ('delvo_sp', 'Delvo SP')], max_length=20, verbose_name='Método de inhibidores'),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='organoleptico_conforme',
            field=models.BooleanField(blank=True, null=True, verbose_name='Control organoléptico conforme'),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='visualizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisissilo',
            name='visualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_silo_visualizados', to=settings.AUTH_USER_MODEL, verbose_name='Visualizado por'),
        ),
    ]
