# Generated by Django 6.0.7 on 2026-08-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0024_limpiar_autofirmas_analisis_silo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosilo',
            name='origen_tipo',
            field=models.CharField(blank=True, choices=[('recepcion', 'Recepción'), ('estandarizacion', 'Estandarización'), ('descremacion', 'Descremación'), ('lote', 'Consumo de lote'), ('transferencia', 'Transferencia'), ('produccion', 'Producción'), ('merma', 'Merma'), ('devolucion', 'Devolución'), ('rework', 'Reproceso'), ('ajuste', 'Ajuste manual')], max_length=20, verbose_name='Origen'),
        ),
    ]
