# Generated by Django 6.0.7 on 2026-08-04 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0010_alter_bodega_area_alter_ciclocip_area_and_more'),
        ('maestros', '0010_sembrar_equipos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva'), ('inspeccion', 'Inspección')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('asignada', 'Asignada'), ('ejecucion', 'En ejecución'), ('espera', 'En espera'), ('prueba', 'En prueba'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=20)),
                ('descripcion', models.TextField()),
                ('prioridad', models.PositiveSmallIntegerField(default=3)),
                ('programada_para', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('termino', models.DateTimeField(blank=True, null=True)),
                ('minutos_parada', models.PositiveIntegerField(default=0)),
                ('prueba_conforme', models.BooleanField(blank=True, null=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_mantenimiento_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='maestros.equipo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['estado', '-prioridad', 'programada_para'],
            },
        ),
        migrations.CreateModel(
            name='FallaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detectada_en', models.DateTimeField(db_index=True)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('descripcion', models.TextField()),
                ('detuvo_produccion', models.BooleanField(default=False)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallas', to='maestros.equipo')),
                ('reportada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fallas_reportadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fallas', to='mantenimiento.ordentrabajo')),
            ],
            options={
                'ordering': ['-detectada_en'],
            },
        ),
        migrations.CreateModel(
            name='PlanPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('frecuencia_dias', models.PositiveIntegerField()),
                ('duracion_estimada_min', models.PositiveIntegerField(default=60)),
                ('ultima_ejecucion', models.DateField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateField(db_index=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_preventivos', to='maestros.equipo')),
            ],
            options={
                'ordering': ['proxima_ejecucion', 'equipo'],
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='mantenimiento.planpreventivo'),
        ),
        migrations.CreateModel(
            name='RepuestoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_mantenimiento', to='inventario.insumo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos', to='mantenimiento.ordentrabajo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='planpreventivo',
            constraint=models.UniqueConstraint(fields=('equipo', 'nombre'), name='plan_preventivo_unico_equipo'),
        ),
        migrations.AddConstraint(
            model_name='planpreventivo',
            constraint=models.CheckConstraint(condition=models.Q(('frecuencia_dias__gt', 0)), name='plan_frecuencia_positiva'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['equipo', 'estado', 'programada_para'], name='mantenimien_equipo__e6369d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.CheckConstraint(condition=models.Q(('prioridad__gte', 1), ('prioridad__lte', 5)), name='ot_prioridad_entre_1_y_5'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.CheckConstraint(condition=models.Q(('termino__isnull', True), ('inicio__isnull', True), ('termino__gt', models.F('inicio')), _connector='OR'), name='ot_termino_posterior_inicio'),
        ),
        migrations.AddConstraint(
            model_name='repuestoutilizado',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='repuesto_cantidad_positiva'),
        ),
    ]
