# Generated by Django 6.0.7 on 2026-08-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_merge_ramas_de_inventario'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestoutilizado',
            name='entrega',
            field=models.ForeignKey(blank=True, help_text='La línea de entrega con que bodega lo despachó. Sin ella el consumo no tiene respaldo en el libro de inventario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repuestos_mantenimiento', to='inventario.detalleentregaproduccion', verbose_name='Entrega de bodega que lo respalda'),
        ),
    ]
