# Generated by Django 6.0.7 on 2026-07-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Mandante',
                'verbose_name_plural': 'Mandantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=60, verbose_name='Código')),
                ('nombre', models.CharField(max_length=180, verbose_name='Nombre')),
                ('familia', models.CharField(choices=[('polvo', 'Polvo'), ('crema', 'Crema'), ('liquido', 'Líquido'), ('otro', 'Otro')], max_length=20, verbose_name='Familia')),
                ('naturaleza', models.CharField(choices=[('materia_prima', 'Materia prima'), ('intermedio', 'Intermedio'), ('terminado', 'Terminado')], default='terminado', help_text='Dónde está en la cadena: materia prima, intermedio o terminado', max_length=20, verbose_name='Naturaleza')),
                ('unidad_base', models.CharField(choices=[('kg', 'Kilogramos'), ('L', 'Litros')], default='kg', help_text='Unidad en que se mide: la leche en litros, el polvo y la crema en kilos', max_length=5, verbose_name='Unidad base')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='maestros.mandante', verbose_name='Mandante')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('vigente_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Vacío = vigente indefinidamente', null=True, verbose_name='Vigente hasta')),
                ('rangos', models.JSONField(default=dict, help_text='{"humedad": {"min": 2.5, "max": 4.0, "obligatorio": true}, ...}', verbose_name='Rangos por parámetro')),
                ('fuente', models.CharField(blank=True, help_text='Documento o acuerdo que respalda la especificación', max_length=250, verbose_name='Fuente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones', to='maestros.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Especificación de calidad',
                'verbose_name_plural': 'Especificaciones de calidad',
                'ordering': ['producto__nombre', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('nombre', 'mandante'), name='producto_unico_por_mandante'),
        ),
        migrations.AddConstraint(
            model_name='especificacion',
            constraint=models.UniqueConstraint(fields=('producto', 'version'), name='especificacion_version_unica_por_producto'),
        ),
    ]
