# Generated by Django 6.0.7 on 2026-07-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=40, verbose_name='Número')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(default='Camión', max_length=60, verbose_name='Tipo')),
                ('capacidad_l', models.DecimalField(blank=True, decimal_places=2, help_text='En litros', max_digits=12, null=True, verbose_name='Capacidad')),
                ('transportista', models.CharField(blank=True, max_length=150, verbose_name='Transportista')),
                ('chofer_am', models.CharField(blank=True, max_length=150, verbose_name='Chofer A.M.')),
                ('chofer_pm', models.CharField(blank=True, max_length=150, verbose_name='Chofer P.M.')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('silo', 'Silo'), ('tk_ld', 'TK Leche descremada'), ('tk_crema', 'TK Crema')], max_length=20, verbose_name='Tipo')),
                ('capacidad_l', models.DecimalField(decimal_places=2, help_text='En litros', max_digits=12, verbose_name='Capacidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Silo / estanque',
                'verbose_name_plural': 'Silos y estanques',
                'ordering': ['codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacidad_l__gte', 0)), name='silo_capacidad_no_negativa')],
            },
        ),
    ]
