# Generated by Django 6.0.7 on 2026-07-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_vehiculo_silo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLiberacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Ej: CCAA.Calidad.FORM.016.02', max_length=80, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('aplica_a', models.JSONField(default=list, help_text='Familias de producto que lo exigen: ["polvo", "crema"]', verbose_name='Aplica a')),
                ('instruccion', models.TextField(blank=True, help_text='Qué debe verificar quien lo completa', verbose_name='Instrucción')),
                ('plantilla', models.JSONField(blank=True, default=list, help_text='[{"clave": "mg", "etiqueta": "Materia grasa", "tipo": "decimal", "req": true, "parametro": "mg"}, ...]. Vacía = solo atestación', verbose_name='Plantilla del formulario')),
                ('fuente', models.CharField(blank=True, help_text='De dónde salió la plantilla. Marque las provisorias', max_length=250, verbose_name='Fuente')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición en el checklist', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento de liberación',
                'verbose_name_plural': 'Documentos de liberación',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('codigo',), name='documento_liberacion_codigo_unico')],
            },
        ),
    ]
