# Generated by Django 6.0.7 on 2026-07-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_documentoliberacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoliberacion',
            name='area',
            field=models.CharField(blank=True, choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad')], help_text='Etapa del flujo que genera el registro', max_length=20, verbose_name='Área de origen'),
        ),
    ]
