# Generated by Django 6.0.7 on 2026-07-31 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_sembrar_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('cantidad_base', models.DecimalField(decimal_places=3, default=1, help_text='Los componentes rinden esta cantidad de producto', max_digits=12, verbose_name='Cantidad base')),
                ('vigente_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Vacío = vigente indefinidamente', null=True, verbose_name='Vigente hasta')),
                ('fuente', models.CharField(blank=True, help_text='Documento o acuerdo que respalda la receta', max_length=250, verbose_name='Fuente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='maestros.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['producto__nombre', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RecetaComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('L', 'Litros')], help_text='Debe coincidir con la unidad base del componente', max_length=5, verbose_name='Unidad')),
                ('merma', models.DecimalField(decimal_places=2, default=0, help_text='En %. Aumenta la cantidad necesaria del componente', max_digits=6, verbose_name='Merma')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_recetas', to='maestros.producto', verbose_name='Componente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='maestros.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Componente de receta',
                'verbose_name_plural': 'Componentes de receta',
                'ordering': ['receta', 'producto__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='receta',
            constraint=models.UniqueConstraint(fields=('producto', 'version'), name='receta_version_unica_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='receta',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_base__gt', 0)), name='receta_cantidad_base_positiva'),
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.UniqueConstraint(fields=('receta', 'producto'), name='componente_unico_por_receta'),
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='componente_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.CheckConstraint(condition=models.Q(('merma__gte', 0)), name='componente_merma_no_negativa'),
        ),
    ]
