# Generated by Django 6.0.7 on 2026-07-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_receta_recetacomponente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandante',
            name='codigo_cliente',
            field=models.CharField(blank=True, choices=[('no_definido', 'Cliente no definido (producto propio CCAA)'), ('nestle', 'Nestlé'), ('colun', 'Colun'), ('soprole', 'Soprole')], help_text='Qué cliente representa este mandante dentro del SKU. Sin esto, sus productos no pueden generar SKU.', max_length=20, verbose_name='Código de cliente (SKU)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('leche_polvo', 'Leche en polvo'), ('precondensado', 'Precondensado'), ('crema', 'Crema'), ('mantequilla', 'Mantequilla'), ('materiales_diversos', 'Materiales diversos'), ('leche_fresca_est', 'Leche fresca estandarizada'), ('suero', 'Suero'), ('extracto_malta', 'Extracto de malta'), ('lp_instantanea', 'Leche en polvo instantánea'), ('lp_con_lecitina', 'Leche en polvo con lecitina'), ('leche_fluida', 'Leche fluida')], max_length=25, verbose_name='Categoría (SKU)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='formato',
            field=models.CharField(blank=True, choices=[('granel', 'Granel'), ('saco_25kg', 'Saco 25 kg'), ('caja_20kg', 'Caja 20 kg')], max_length=15, verbose_name='Formato (SKU)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='mercado',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('exportacion', 'Exportación')], default='local', max_length=15, verbose_name='Mercado (SKU)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='naturaleza_comercial',
            field=models.CharField(blank=True, choices=[('servicio_terceros', 'Servicio a terceros'), ('producto_propio', 'Producto propio')], max_length=20, verbose_name='Naturaleza comercial (SKU)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('entera', 'Entera'), ('semidescremada', 'Semidescremada'), ('descremada', 'Descremada'), ('con_sal', 'Con sal'), ('sin_sal', 'Sin sal'), ('sin_especificar', 'Sin especificar'), ('no_definido', 'No definido'), ('estandarizada', 'Estandarizada')], max_length=20, verbose_name='Tipo (SKU)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='variante',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Correlativo de dos dígitos para desempatar dos productos que comparten los seis segmentos. Déjalo vacío salvo que haga falta.', null=True, verbose_name='Variante (SKU)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Se genera solo desde los atributos del SKU. Se puede escribir a mano para registrar un código antiguo, pero al completar los atributos se recalcula.', max_length=60, verbose_name='SKU'),
        ),
    ]
