# Generated by Django 6.0.7 on 2026-07-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_mandante_codigo_cliente_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Derivado de los atributos de abajo; se recalcula al guardar. Un producto sin ellos conserva el código que tenga, para poder registrar los códigos antiguos de planta.', max_length=60, verbose_name='SKU'),
        ),
    ]
