# Generated by Django 6.0.7 on 2026-07-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_alter_producto_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Identificador estable. No se cambia: la planificación lo referencia.', max_length=40, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('linea', 'Línea'), ('carga', 'Carga'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('consume_leche', models.BooleanField(default=False, help_text='Solo los evaporadores. Marcarlo en una línea que recibe lo que el evaporador ya produjo restaría la misma leche dos veces.', verbose_name='Consume leche del balance')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Posición en la carta Gantt, de arriba hacia abajo.', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Equipo / máquina',
                'verbose_name_plural': 'Equipos y máquinas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
