# Generated by Django 6.0.7 on 2026-07-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_sembrar_equipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoliberacion',
            name='evidencia',
            field=models.JSONField(blank=True, default=dict, help_text='Qué registro del sistema da por cumplido este documento: {"fuente": "monitoreo_ppro", "tipo": "detector_metales"}. Vacío = lo marca una persona.', verbose_name='Se cumple con el dato'),
        ),
    ]
