# Generated by Django 6.0.7 on 2026-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0014_checklist_ce_por_evaporador'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoliberacion',
            name='frecuencia',
            field=models.CharField(choices=[('por_lote', 'Por lote'), ('por_turno', 'Por turno'), ('por_ciclo', 'Por ciclo'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('segun_programa', 'Según programa')], default='por_lote', help_text='Decide dónde vive el registro: por lote va en el expediente del lote; el resto pertenece al equipo y su período.', max_length=20, verbose_name='Frecuencia'),
        ),
    ]
