# Generated by Django 6.0.7 on 2026-08-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0017_equipos_torres_y_envasadoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('evaporador', 'Evaporador'), ('torre', 'Torre de secado'), ('envasadora', 'Envasadora'), ('linea', 'Línea'), ('carga', 'Carga'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
