# Generated by Django 6.0.7 on 2026-08-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_consumoproducto_consumo_unico_producto_insumo_and_more'),
        ('maestros', '0019_evidencia_por_equipo_del_maestro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetacomponente',
            options={'ordering': ['receta', 'producto__nombre', 'insumo__nombre'], 'verbose_name': 'Componente de receta', 'verbose_name_plural': 'Componentes de receta'},
        ),
        migrations.RemoveConstraint(
            model_name='recetacomponente',
            name='componente_unico_por_receta',
        ),
        migrations.AddField(
            model_name='recetacomponente',
            name='insumo',
            field=models.ForeignKey(blank=True, help_text='Si el componente se compra y se descuenta de bodega.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_recetas', to='inventario.insumo', verbose_name='Insumo'),
        ),
        migrations.AlterField(
            model_name='recetacomponente',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Si el componente se transforma aquí. Deja vacío si es un insumo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_recetas', to='maestros.producto', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='recetacomponente',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('L', 'Litros'), ('un', 'Unidades')], help_text='Debe coincidir con la unidad base del componente', max_length=5, verbose_name='Unidad'),
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.UniqueConstraint(fields=('receta', 'producto'), name='componente_unico_por_receta', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.UniqueConstraint(fields=('receta', 'insumo'), name='componente_insumo_unico_por_receta', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('insumo__isnull', True), ('producto__isnull', False)), models.Q(('insumo__isnull', False), ('producto__isnull', True)), _connector='OR'), name='componente_es_producto_o_insumo'),
        ),
    ]
