# Generated by Django 6.0.7 on 2026-08-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0022_mandante_unico_por_codigo_cliente'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mandante',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_cliente', ''), _negated=True), fields=('codigo_cliente',), name='mandante_unico_por_codigo_cliente'),
        ),
    ]
