# Generated by Django 6.0.7 on 2026-08-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0023_mandante_mandante_unico_por_codigo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='consume_materiales',
            field=models.BooleanField(default=False, help_text='Solo el equipo del final de la cadena: la torre o la línea que envasa. Marcarlo también en el evaporador que la alimenta haría que el MRP pidiera los sacos dos veces.', verbose_name='Consume materiales del MRP'),
        ),
    ]
