# Generated by Django 6.0.7 on 2026-08-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_insumo_stock_actual'),
        ('maestros', '0025_sembrar_consume_materiales'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recetacomponente',
            name='componente_unico_por_receta',
        ),
        migrations.RemoveConstraint(
            model_name='recetacomponente',
            name='componente_insumo_unico_por_receta',
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.UniqueConstraint(fields=('receta', 'producto'), name='componente_unico_por_receta'),
        ),
        migrations.AddConstraint(
            model_name='recetacomponente',
            constraint=models.UniqueConstraint(fields=('receta', 'insumo'), name='componente_insumo_unico_por_receta'),
        ),
    ]
