# Generated by Django 6.0.7 on 2026-08-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0027_tenant_maestros'),
        ('usuarios', '0014_alter_perfilusuario_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='silo',
            name='silo_capacidad_no_negativa',
        ),
        migrations.AddField(
            model_name='silo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('recibiendo', 'Recibiendo'), ('en_uso', 'En uso'), ('reservado', 'Reservado'), ('bloqueado_calidad', 'Bloqueado por Calidad'), ('pendiente_cip', 'Pendiente de CIP'), ('en_cip', 'En CIP'), ('fuera_servicio', 'Fuera de servicio')], db_index=True, default='disponible', max_length=30, verbose_name='Estado operacional'),
        ),
        migrations.AddField(
            model_name='silo',
            name='producto_actual',
            field=models.ForeignKey(blank=True, help_text='Producto declarado; el volumen siempre se deriva de movimientos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='silos_actuales', to='maestros.producto'),
        ),
        migrations.AddField(
            model_name='silo',
            name='temperatura_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura actual (°C)'),
        ),
        migrations.AddField(
            model_name='silo',
            name='ultima_limpieza',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='silo',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_l__gt', 0)), name='silo_capacidad_positiva'),
        ),
    ]
