# Generated by Django 6.0.7 on 2026-08-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0029_producto_sku_unico'),
        ('usuarios', '0015_alter_perfilusuario_alcance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sigla',
            field=models.CharField(blank=True, help_text='Dos o tres caracteres que identifican la máquina dentro del código de lote (E1, S2, R4). Solo la necesitan los equipos que encabezan una corrida.', max_length=3, verbose_name='Sigla'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(condition=models.Q(('sigla', ''), _negated=True), fields=('sucursal', 'sigla'), name='equipo_sigla_unica_sucursal'),
        ),
    ]
