# Generated by Django 6.0.7 on 2026-09-03 19:24

from django.db import migrations, models


def clasificar_materiales_de_empaque(apps, schema_editor):
    Componente = apps.get_model("maestros", "RecetaComponente")
    Componente.objects.filter(insumo__categoria="empaque").update(fase="envasado")


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_detalledespachogranel_movimiento_silo_and_more'),
        ('maestros', '0035_equipo_tipo_descremadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetacomponente',
            name='fase',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('envasado', 'Envasado')], default='proceso', help_text='Proceso se descuenta al cerrar el lote; Envasado se descuenta cuando se generan físicamente sus pallets.', max_length=20, verbose_name='Etapa de consumo'),
        ),
        migrations.RunPython(
            clasificar_materiales_de_empaque,
            migrations.RunPython.noop,
        ),
    ]
