# Generated by Django 6.0.7 on 2026-09-04 14:11

import django.db.models.deletion
from django.db import migrations, models


def sembrar_formatos_existentes(apps, schema_editor):
    Formato = apps.get_model("maestros", "FormatoEnvasado")
    Producto = apps.get_model("maestros", "Producto")
    Equipo = apps.get_model("maestros", "Equipo")
    configuraciones = {
        "saco_25kg": ("saco-25kg", "Saco 25 kg", "25", 20),
        "caja_20kg": ("caja-20kg", "Caja 20 kg", "20", 25),
    }
    for producto in Producto.objects.filter(
        activo=True, naturaleza="terminado", formato__in=configuraciones,
    ).select_related("mandante"):
        codigo, nombre, kg_neto, maximo = configuraciones[producto.formato]
        formato, _ = Formato.objects.get_or_create(
            producto_id=producto.pk,
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "kg_neto": kg_neto,
                "unidades_maximas_pallet": maximo,
                "activo": True,
            },
        )
        tipos_equipo = ["linea"] if producto.formato == "caja_20kg" else [
            "envasadora"
        ]
        equipos = Equipo.objects.filter(
            sucursal__empresa_id=producto.mandante.empresa_id,
            activo=True,
            tipo__in=tipos_equipo,
        )
        formato.equipos.add(*equipos)


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0036_recetacomponente_fase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoEnvasado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('kg_neto', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidades_maximas_pallet', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('equipos', models.ManyToManyField(blank=True, related_name='formatos_envasado', to='maestros.equipo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formatos_envasado', to='maestros.producto')),
            ],
            options={
                'ordering': ['producto__nombre', 'kg_neto', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'codigo'), name='formato_envase_codigo_unico_producto'), models.CheckConstraint(condition=models.Q(('kg_neto__gt', 0)), name='formato_envase_kg_positivo'), models.CheckConstraint(condition=models.Q(('unidades_maximas_pallet__gt', 0)), name='formato_envase_unidades_positivas')],
            },
        ),
        migrations.RunPython(
            sembrar_formatos_existentes, migrations.RunPython.noop
        ),
    ]
