# Generated by Django 6.0.7 on 2026-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0037_formatoenvasado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoenvasado',
            name='tipo_unidad_logistica',
            field=models.CharField(choices=[('pallet', 'Pallet'), ('big_bag', 'Big Bag')], default='pallet', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(blank=True, choices=[('granel', 'Granel'), ('saco_25kg', 'Saco 25 kg'), ('caja_20kg', 'Caja 20 kg'), ('big_bag', 'Big Bag')], max_length=15, verbose_name='Formato (SKU)'),
        ),
    ]
