# Generated by Django 6.0.7 on 2026-07-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_roles_del_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Administrador de área'), ('trabajador', 'Trabajador')], default='trabajador', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='area',
            field=models.CharField(blank=True, choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('administracion', 'Administración general')], max_length=30),
        ),
    ]
