# Generated by Django 6.0.7 on 2026-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_nivel_alter_perfilusuario_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='area',
            field=models.CharField(blank=True, choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('administracion', 'Administración general')], max_length=30),
        ),
    ]
