# Generated by Django 6.0.7 on 2026-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_sincronizar_staff_administradores_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='area',
            field=models.CharField(blank=True, choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración general')], max_length=30),
        ),
    ]
