# Generated by Django 6.0.7 on 2026-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_tabla_de_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuario declarado')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección')),
                ('exito', models.BooleanField(default=False, verbose_name='Correcto')),
                ('motivo', models.CharField(blank=True, max_length=60, verbose_name='Motivo del rechazo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Intento de acceso',
                'verbose_name_plural': 'Intentos de acceso',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='usuarios_in_usuario_8b11b6_idx'), models.Index(fields=['ip', '-fecha_hora'], name='usuarios_in_ip_45567d_idx')],
            },
        ),
    ]
