# Generated by Django 6.0.7 on 2026-08-12 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_administracion_alcance_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('produccion', 'Producción'), ('calidad', 'Calidad'), ('operario', 'Operario'), ('admin', 'Administrador'), ('lectura', 'Solo lectura')], default='lectura', max_length=20),
        ),
        migrations.CreateModel(
            name='AreaDePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('recepcion', 'Recepción'), ('condensacion', 'Condensación'), ('secado', 'Secado'), ('envase', 'Envase'), ('calidad', 'Calidad'), ('bodega', 'Bodega'), ('compras', 'Compras'), ('despacho', 'Despacho'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración general')], max_length=30, verbose_name='Área')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_adicionales', to='usuarios.perfilusuario', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Área adicional',
                'verbose_name_plural': 'Áreas adicionales',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'area'), name='area_adicional_unica_por_perfil')],
            },
        ),
    ]
