# Generated by Django 6.0.7 on 2026-08-17 22:23

import django.db.models.deletion
from django.db import migrations, models


def unificar_perfiles(apps, schema_editor):
    PerfilUsuario = apps.get_model("usuarios", "PerfilUsuario")
    PerfilUsuario.objects.update(alcance="empresa", sucursal=None)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_perfilusuario_options'),
    ]

    operations = [
        migrations.RunPython(unificar_perfiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='perfilusuario',
            name='alcance',
            field=models.CharField(choices=[('sucursal', 'Sucursal'), ('empresa', 'Toda la empresa')], default='empresa', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='usuarios.sucursal'),
        ),
    ]
