# Generated by Django 6.0.7 on 2026-08-19 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_perfilusuario_alcance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('produccion_orden_crear', 'Puede crear órdenes de producción'), ('produccion_orden_editar', 'Puede editar órdenes de producción'), ('produccion_lote_cerrar', 'Puede cerrar lotes de producción'), ('produccion_lote_anular', 'Puede anular lotes de producción'), ('secado_proceso_iniciar', 'Puede iniciar procesos de secado'), ('secado_proceso_cerrar', 'Puede cerrar procesos de secado'), ('calidad_lote_liberar', 'Puede liberar lotes por Calidad'), ('calidad_lote_bloquear', 'Puede bloquear lotes por Calidad'), ('inventario_transferir', 'Puede transferir inventario'), ('inventario_ajustar', 'Puede solicitar ajustes de inventario'), ('despacho_crear', 'Puede crear solicitudes de despacho'), ('despacho_autorizar', 'Puede autorizar despachos'), ('auditoria_exportar', 'Puede exportar registros de auditoría'), ('reset_password', 'Puede restablecer contraseñas'), ('manage_sessions', 'Puede consultar sesiones activas'), ('force_logout', 'Puede cerrar sesiones ajenas'), ('change_roles', 'Puede cambiar roles y permisos')], 'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuario'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar la contraseña'),
        ),
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(db_index=True, max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='usuarios_ev_usuario_05a516_idx')],
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.CharField(blank=True, choices=[('logout', 'Cierre del usuario'), ('inactividad', 'Expirada por inactividad'), ('absoluta', 'Expirada por antigüedad'), ('admin', 'Cerrada por administrador'), ('password', 'Cambio de contraseña'), ('reset_password', 'Restablecimiento de contraseña'), ('desactivacion', 'Usuario desactivado'), ('bloqueo', 'Cuenta bloqueada')], max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_cerradas_por_mi', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['fecha_cierre', '-ultima_actividad'], name='usuarios_se_fecha_c_fba451_idx'), models.Index(fields=['usuario', '-fecha_inicio'], name='usuarios_se_usuario_e97717_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_cierre__isnull', True)), fields=('usuario',), name='una_sesion_abierta_por_usuario')],
            },
        ),
    ]
