# Generated by Django 6.0.7 on 2026-07-31 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150, verbose_name='Usuario (al momento)')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('borrado', 'Borrado')], max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(db_index=True, max_length=100, verbose_name='Modelo')),
                ('etiqueta_modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo (nombre)')),
                ('objeto_id', models.CharField(db_index=True, max_length=40, verbose_name='ID del objeto')),
                ('objeto_desc', models.CharField(blank=True, max_length=300, verbose_name='Objeto')),
                ('cambios', models.JSONField(blank=True, default=dict, help_text='{"kg_producidos": ["1000.00", "1200.00"]}', verbose_name='Cambios')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('origen', models.CharField(blank=True, max_length=20, verbose_name='Origen')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha_hora', '-id'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='auditoria_r_modelo_e0db67_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='auditoria_r_usuario_0c1b0a_idx')],
            },
        ),
    ]
